#!/usr/bin/env python3
"""Thunderline preview exporter (Pages player source, stdlib only).

Reads the full-rate deterministic render in ``dist/`` (44.1 kHz 16-bit mono
``master.wav`` plus the four stem buses) and derives the small committed
tree the Pages player serves::

    player/audio/master.wav           - 22.05 kHz 16-bit mono preview master
    player/audio/stems/<name>.wav     - 22.05 kHz 8-bit mono preview stems
    player/audio/lyrics.json          - lyric timing copy (identical bytes)
    player/audio/song.json            - score copy (identical bytes)
    player/audio/song.mid             - MIDI copy (identical bytes)
    player/audio/sheet.html           - lead-sheet copy (identical bytes)
    player/audio/preview.json         - provenance (hashes back to dist/)

Why previews instead of the full-rate files: ``dist/`` plus ``*.wav`` are
lab-global gitignored build output, and five 13.7 MB buses are too heavy to
ship to browsers. The previews are honest downsamples (2-tap lowpass,
even-phase, the same math as the render fallback) generated by this script,
never hand-placed: ``preview.json`` pins the SHA-256 of every ``dist/``
source so any checkout can verify the player audio matches the local render.

Determinism contract: no wall clock, no network, no randomness. Fixed WAV
headers, deterministic float math and rounding. Exporting twice produces
bit-identical bytes, pinned by ``tests/test_player.py``.
"""
import array
import hashlib
import json
import os
import shutil
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DIST = os.path.join(ROOT, "dist")
SCORE = os.path.join(ROOT, "score")
AUDIO = os.path.join(ROOT, "player", "audio")

MASTER_RATE = 22050
STEM_RATE = 22050
STEMS = ("vocals", "guitars", "bass", "drums")


def sha_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def read_mono16(path):
    """Parse a mono 16-bit PCM WAV; return (sample_rate, array('h'))."""
    with open(path, "rb") as f:
        data = f.read()
    if data[0:4] != b"RIFF":
        raise ValueError("missing RIFF")
    if data[8:12] != b"WAVE":
        raise ValueError("missing WAVE")
    if data[12:16] != b"fmt ":
        raise ValueError("missing fmt")
    (fmt_len, audio, ch, sr, _br, _ba, bits) = struct.unpack(
        "<IHHIIHH", data[16:36])
    if fmt_len != 16:
        raise ValueError("unexpected fmt len: %r" % fmt_len)
    if not (audio == 1 and ch == 1 and bits == 16):
        raise ValueError("not mono 16-bit PCM")
    if data[36:40] != b"data":
        raise ValueError("missing data chunk")
    (nbytes,) = struct.unpack("<I", data[40:44])
    raw = data[44:44 + nbytes]
    if len(raw) != nbytes:
        raise ValueError("truncated data chunk")
    return sr, array.array("h", raw)


def downsample_half(samples):
    """2:1 downsample with a 2-tap lowpass on even phase; returns floats."""
    n = len(samples) - (len(samples) % 2)
    out = [0.0] * (n // 2)
    for i in range(n // 2):
        out[i] = (samples[2 * i] + samples[2 * i + 1]) * (0.5 / 32767.0)
    return out


def clamp(v):
    if v > 1.0:
        return 1.0
    if v < -1.0:
        return -1.0
    return v


def write_wav_fixed(path, ints, sample_rate, bits):
    """Write mono PCM with a fixed 44-byte header (no timestamps)."""
    n = len(ints)
    if bits == 16:
        body = struct.pack("<%dh" % n, *ints)
    elif bits == 8:
        body = bytes(ints)
    else:
        raise ValueError("unsupported bits: %r" % bits)
    with open(path, "wb") as f:
        f.write(b"RIFF")
        f.write(struct.pack("<I", 36 + n * (bits // 8)))
        f.write(b"WAVEfmt ")
        f.write(struct.pack("<IHHIIHH", 16, 1, 1, sample_rate,
                            sample_rate * (bits // 8), bits // 8, bits))
        f.write(b"data")
        f.write(struct.pack("<I", n * (bits // 8)))
        f.write(body)


def export_all(dist_dir=DIST, out_dir=AUDIO):
    for rel in ["master.wav"] + [os.path.join("stems", n + ".wav")
                                 for n in STEMS]:
        p = os.path.join(dist_dir, rel)
        if not os.path.isfile(p):
            print("export_preview: missing %s (run tools/render.py first)"
                  % p, file=sys.stderr)
            return 1
    try:
        sr, master = read_mono16(os.path.join(dist_dir, "master.wav"))
        stems = {}
        for name in STEMS:
            srate, buf = read_mono16(
                os.path.join(dist_dir, "stems", name + ".wav"))
            if srate != sr:
                print("export_preview: stem rate mismatch: %s" % name,
                      file=sys.stderr)
                return 1
            stems[name] = buf
    except (ValueError, OSError) as e:
        print("export_preview: unreadable dist audio: %s" % e,
              file=sys.stderr)
        return 1
    if sr != 44100:
        print("export_preview: expected 44.1 kHz dist, got %r" % sr,
              file=sys.stderr)
        return 1

    os.makedirs(os.path.join(out_dir, "stems"), exist_ok=True)

    master_half = downsample_half(master)
    master16 = [int(round(clamp(v) * 32767.0)) for v in master_half]
    write_wav_fixed(os.path.join(out_dir, "master.wav"), master16,
                    MASTER_RATE, 16)

    for name in STEMS:
        half = downsample_half(stems[name])
        stem8 = [int(round((clamp(v) * 0.5 + 0.5) * 255.0)) for v in half]
        write_wav_fixed(os.path.join(out_dir, "stems", name + ".wav"),
                        stem8, STEM_RATE, 8)

    for rel in ("lyrics.json", "song.mid", "sheet.html"):
        src = os.path.join(dist_dir, rel)
        if not os.path.isfile(src):
            print("export_preview: missing %s (run tools/export_score.py "
                  "first)" % src, file=sys.stderr)
            return 1
        shutil.copyfile(src, os.path.join(out_dir, rel))
    shutil.copyfile(os.path.join(SCORE, "song.json"),
                    os.path.join(out_dir, "song.json"))

    manifest = {
        "title": "Thunderline",
        "generator": "tools/export_preview.py (stdlib only)",
        "note": ("Preview-quality audio for the Pages player: 22.05 kHz "
                 "mono downsamples of the full-rate dist/ render. "
                 "Run bash thunderline/repro.sh for bit-identical masters."),
        "masterRate": MASTER_RATE,
        "masterBits": 16,
        "stemRate": STEM_RATE,
        "stemBits": 8,
        "sources": {},
    }
    for rel in (["master.wav"] + [os.path.join("stems", n + ".wav")
                                  for n in STEMS]):
        manifest["sources"][rel] = sha_file(os.path.join(dist_dir, rel))
    manifest["scoreSha256"] = sha_file(os.path.join(SCORE, "song.json"))
    manifest["files"] = {}
    for rel in (["master.wav", "lyrics.json", "song.json", "song.mid",
                 "sheet.html"]
                + [os.path.join("stems", n + ".wav") for n in STEMS]):
        manifest["files"][rel] = sha_file(os.path.join(out_dir, rel))
    with open(os.path.join(out_dir, "preview.json"), "w",
              encoding="utf-8") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
        f.write("\n")
    print("exported preview audio + score copies to %s" % out_dir)
    return 0


def main(argv):
    dist_dir = DIST
    out_dir = AUDIO
    args = list(argv)
    while args:
        a = args.pop(0)
        if a == "--dist":
            if not args:
                print("export_preview: --dist needs a directory",
                      file=sys.stderr)
                return 2
            dist_dir = args.pop(0)
        elif a == "--out":
            if not args:
                print("export_preview: --out needs a directory",
                      file=sys.stderr)
                return 2
            out_dir = args.pop(0)
        else:
            print("export_preview: unknown arg %r" % a, file=sys.stderr)
            return 2
    return export_all(dist_dir, out_dir)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
