#!/usr/bin/env python3
"""
Export trained neural codec weights to int16 fixed-point C++ header.

Converts a PyTorch checkpoint to baked int16 constants (Q=1024) following
the same pattern as option_c_data.inc, learned_ctx_data.inc, etc.

Usage:
    python3 export_weights.py --checkpoint /tmp/neural_weights/phase3_final.pt \\
        --output ../src/codec/neural_codec_data.inc

Architecture (inference-time):
  g_a: 4 conv layers (3x3), GDN activations
  h_a: 3 conv layers (3x3), GDN activations
  g_s: 4 conv layers (3x3), IGDN activations
  h_s: 2 conv layers (3x3), ReLU + linear

Weight format: int16 Q=1024 (multiply float by 1024, round, clip to [-32768, 32767]).
"""

import argparse
import os
import sys
import numpy as np

try:
    import torch
except ImportError:
    print("ERROR: PyTorch required. Install with: pip install torch", file=sys.stderr)
    sys.exit(1)


Q = 1024  # Fixed-point quantization factor


def float_to_int16(arr):
    """Convert float array to int16 with Q=1024 quantization."""
    scaled = arr * Q
    clipped = np.clip(np.round(scaled), -32768, 32767)
    return clipped.astype(np.int16)


def conv_to_int16(weight, bias=None):
    """Extract int16 weights and bias from a Conv2d layer."""
    w = weight.detach().cpu().numpy()
    # PyTorch Conv2d weight shape: (out_ch, in_ch, kH, kW)
    # We want: (out_ch, in_ch, kH, kW) - same order
    w_int16 = float_to_int16(w)
    b_int16 = None
    if bias is not None:
        b = bias.detach().cpu().numpy()
        b_int16 = float_to_int16(b)
    return w_int16, b_int16


def gdn_to_int16(gdn_layer):
    """Extract GDN beta parameter as int16."""
    beta = gdn_layer.beta.detach().cpu().numpy()
    return float_to_int16(beta)


def write_array(f, name, arr, dtype="int16_t"):
    """Write a C++ array declaration."""
    f.write(f"constexpr {dtype} {name}[] = {{\n")
    flat = arr.flatten()
    for i in range(0, len(flat), 16):
        chunk = flat[i:i+16]
        vals = ", ".join(str(v) for v in chunk)
        f.write(f"    {vals},\n")
    f.write("};\n\n")


def write_conv_layer(f, prefix, weight, bias=None):
    """Write conv layer weights as C++ arrays."""
    w_int16, b_int16 = conv_to_int16(weight, bias)
    write_array(f, f"{prefix}_w", w_int16)
    if b_int16 is not None:
        write_array(f, f"{prefix}_b", b_int16)


def export_model(model, output_path):
    """Export trained model to C++ header."""
    state = model.state_dict()

    with open(output_path, 'w') as f:
        f.write("// Neural codec baked weights (generated by export_weights.py).\n")
        f.write("// Full neural codec end-to-end (E1, issue #226).\n")
        f.write("// Architecture: g_a + h_a + g_s + h_s with GDN activations.\n")
        f.write("// Quantization: int16 Q=1024.\n\n")
        f.write('#pragma once\n\n')
        f.write("#include <cstdint>\n\n")
        f.write("namespace prism::codec {\n\n")

        # g_a: 4 conv layers
        # Layer 0: Conv2d(3, 128, 3, stride=2)
        write_conv_layer(f, "ga_conv0", state["g_a.net.0.weight"], state["g_a.net.0.bias"])
        # Layer 1: Conv2d(128, 128, 3, stride=1)
        write_conv_layer(f, "ga_conv1", state["g_a.net.2.weight"], state["g_a.net.2.bias"])
        # Layer 2: Conv2d(128, 128, 3, stride=2)
        write_conv_layer(f, "ga_conv2", state["g_a.net.4.weight"], state["g_a.net.4.bias"])
        # Layer 3: Conv2d(128, N, 3, stride=1)
        write_conv_layer(f, "ga_conv3", state["g_a.net.6.weight"], state["g_a.net.6.bias"])

        # g_a GDN parameters
        write_array(f, "ga_gdn1_beta", gdn_to_int16(model.g_a.net[1]))
        write_array(f, "ga_gdn2_beta", gdn_to_int16(model.g_a.net[3]))
        write_array(f, "ga_gdn3_beta", gdn_to_int16(model.g_a.net[5]))

        # h_a: 3 conv layers
        write_conv_layer(f, "ha_conv0", state["h_a.net.0.weight"], state["h_a.net.0.bias"])
        write_conv_layer(f, "ha_conv1", state["h_a.net.2.weight"], state["h_a.net.2.bias"])
        write_conv_layer(f, "ha_conv2", state["h_a.net.4.weight"], state["h_a.net.4.bias"])

        # h_a GDN parameters
        write_array(f, "ha_gdn1_beta", gdn_to_int16(model.h_a.net[1]))
        write_array(f, "ha_gdn2_beta", gdn_to_int16(model.h_a.net[3]))

        # g_s: 4 conv layers (mirror of g_a)
        write_conv_layer(f, "gs_conv0", state["g_s.net.0.weight"], state["g_s.net.0.bias"])
        write_conv_layer(f, "gs_conv1", state["g_s.net.2.weight"], state["g_s.net.2.bias"])
        write_conv_layer(f, "gs_conv2", state["g_s.net.4.weight"], state["g_s.net.4.bias"])
        write_conv_layer(f, "gs_conv3", state["g_s.net.6.weight"], state["g_s.net.6.bias"])

        # g_s IGDN parameters
        write_array(f, "gs_igdn1_beta", gdn_to_int16(model.g_s.net[1]))
        write_array(f, "gs_igdn2_beta", gdn_to_int16(model.g_s.net[3]))
        write_array(f, "gs_igdn3_beta", gdn_to_int16(model.g_s.net[5]))

        # h_s: 2 conv layers
        write_conv_layer(f, "hs_conv0", state["h_s.net.0.weight"], state["h_s.net.0.bias"])
        write_conv_layer(f, "hs_conv1", state["h_s.net.2.weight"], state["h_s.net.2.bias"])

        # Model metadata
        f.write("// Model metadata\n")
        f.write(f"constexpr int NEURAL_N = {model.g_a.net[6].out_channels};\n")
        f.write(f"constexpr int NEURAL_M = {model.h_a.net[4].out_channels};\n")
        f.write(f"constexpr int NEURAL_C = 3;\n")
        f.write(f"constexpr int NEURAL_Q = {Q};\n\n")

        # Version info
        f.write("struct NeuralCodecParams {\n")
        f.write("    static constexpr int N = NEURAL_N;\n")
        f.write("    static constexpr int M = NEURAL_M;\n")
        f.write("    static constexpr int C = NEURAL_C;\n")
        f.write("    static constexpr int Q = NEURAL_Q;\n")
        f.write("    static constexpr int G_A_LAYERS = 4;\n")
        f.write("    static constexpr int H_A_LAYERS = 3;\n")
        f.write("    static constexpr int G_S_LAYERS = 4;\n")
        f.write("    static constexpr int H_S_LAYERS = 2;\n")
        f.write("};\n\n")

        f.write("} // namespace prism::codec\n")

    # Compute model size
    size = os.path.getsize(output_path)
    print(f"Written baked weights to {output_path}")
    print(f"Header size: {size} bytes ({size/1024:.1f} KB)")

    # Report weight counts
    total_params = 0
    for k, v in state.items():
        total_params += v.numel()
    print(f"Total parameters: {total_params:,}")
    print(f"Int16 size estimate: {total_params * 2 / 1024:.1f} KB")


def main():
    parser = argparse.ArgumentParser(description="Export neural codec weights to C++ header")
    parser.add_argument("--checkpoint", required=True, help="PyTorch checkpoint path")
    parser.add_argument("--output", required=True, help="Output .inc file path")
    args = parser.parse_args()

    print(f"Loading checkpoint: {args.checkpoint}")

    # Import model class (needs to be importable)
    sys.path.insert(0, os.path.dirname(__file__))
    from train_neural_codec import NeuralCodec

    # Load with CPU mapping
    checkpoint = torch.load(args.checkpoint, map_location='cpu')

    # Determine model dimensions from checkpoint
    N = checkpoint.get("g_a.net.6.weight", torch.zeros(192, 128, 3, 3)).shape[0]
    M = checkpoint.get("h_a.net.4.weight", torch.zeros(192, 128, 3, 3)).shape[0]

    print(f"Model dimensions: N={N}, M={M}")

    model = NeuralCodec(N, M)
    model.load_state_dict(checkpoint)
    model.eval()

    export_model(model, args.output)


if __name__ == "__main__":
    main()
