#pragma once
#include "prism/types.h"
#include "prism/codec/wavelet.h"
#include <cstdint>
#include <vector>

namespace prism::codec {

// Option C: Learned Pyramid Codec (L3C-style, replaces wavelet entirely).
//
// A multi-scale learned analysis/synthesis transform that replaces the fixed
// LeGall 5/3 wavelet. Uses reversible integer lifting with learned MLP predict
// steps, conditioned on decomposition level and orientation. Byte-exact
// reversible (invariant I26): synthesis = inverse(analysis) for every pixel.
//
// With all MLP weights = 0, the transform degenerates to the linear LeGall 5/3,
// so it degrades gracefully to the existing X6b baseline.
//
// Architecture (3 scales):
//   Encoder: pixels -> YCoCg-R -> analysis_transform -> latents
//   Pass 1: collect statistics per (scale, orient, significance_class)
//   Pass 2: transmit delta-coded histograms + code latents with static ANS
//   Decoder: parse histograms -> decode latents -> synthesis_transform -> pixels

// Per-scale MLP predict parameters (integer, Q=1024 fixed-point).
// The MLP predicts the odd samples from the even samples at each scale.
// Input: 2 features (lv, rv) -> hidden 16 -> output 1 (correction).
struct OptionCPredict {
    static constexpr int H = 16;
    static constexpr int Q = 1024;
    // Baked weights (generated by train_option_c.py)
    int16_t W1[H][2] = {};  // input -> hidden
    int16_t b1[H] = {};     // hidden bias
    int16_t W2[H] = {};     // hidden -> output
    int16_t b2 = 0;         // output bias

    // Integer MLP prediction of the Le Gall base correction.
    int32_t predict(int32_t lv, int32_t rv) const;
};

// Per-scale update parameters (integer, Q=1024 fixed-point).
// The update step modifies the even samples using the predicted residuals.
// This is a simple linear function: update = (residual_left + residual_right) >> 1
// (identical to LeGall 5/3 update - the learnability is in the predict step).
struct OptionCUpdate {
    // Linear update with optional learned scale factor.
    // scale_num/scale_den: rational scale factor (default 1/1 = identity).
    int16_t scale_num = 1;
    int16_t scale_den = 1;
};

// Full Option C learned pyramid parameters (baked constants).
struct OptionCParams {
    static constexpr int NUM_SCALES = 3;
    // Per-scale predict MLP (separate weights for rows and columns at each scale).
    OptionCPredict row_predict[NUM_SCALES] = {};
    OptionCPredict col_predict[NUM_SCALES] = {};
    OptionCUpdate row_update[NUM_SCALES] = {};
    OptionCUpdate col_update[NUM_SCALES] = {};
};

// Get the baked parameters (generated by train_option_c.py).
const OptionCParams& baked_option_c_params();

// Forward 1D lifting step: even, odd -> out_even, out_odd.
// Applies predict(even) -> residual = odd - predict(even)
// Then update(even, residual) -> out_even = even + update(residual)
void option_c_forward_1d(const int32_t* even, size_t en,
                         const int32_t* odd, size_t on,
                         int32_t* out_even, int32_t* out_odd,
                         const OptionCPredict& pred, const OptionCUpdate& upd);

// Inverse 1D lifting step: out_even, out_odd -> even, odd.
// Exact inverse of forward_1d (byte-exact reversible, invariant I26).
void option_c_inverse_1d(const int32_t* out_even, size_t en,
                         const int32_t* out_odd, size_t on,
                         int32_t* even, int32_t* odd,
                         const OptionCPredict& pred, const OptionCUpdate& upd);

// Forward 2D analysis transform for one plane.
// Produces NUM_SCALES+1 subbands: LL (coarsest) + (HL, LH, HH) per scale.
struct OptionCSubband {
    enum class Orient : uint8_t { LL = 0, HL = 1, LH = 2, HH = 3 };
    Orient orient = Orient::LL;
    int scale = 0; // 0 = coarsest LL, 1..NUM_SCALES for detail bands
    int w = 0, h = 0;
    std::vector<int32_t> coeffs;
};

// Full analysis: plane -> subbands (3 scales, each with HL/LH/HH + LL).
std::vector<OptionCSubband> option_c_analysis(const std::vector<int32_t>& plane,
                                               uint32_t w, uint32_t h,
                                               const OptionCParams& params);

// Full synthesis: subbands -> plane (exact inverse of analysis).
std::vector<int32_t> option_c_synthesis(const std::vector<OptionCSubband>& subbands,
                                         uint32_t w, uint32_t h,
                                         const OptionCParams& params);

// Frame-level encode/decode using Option C learned pyramid.
// Replaces frame_wavelet_encode for the Option C path.
std::vector<uint8_t> frame_option_c_encode(const Raster& raster, size_t& net_out);
Raster frame_option_c_decode(const std::vector<uint8_t>& bytes);

// CLI: prism enc/dec with --option-c flag.
// prism bench-x --option-c for measurement.

} // namespace prism::codec
