// Generated by Glyphforge 1.0.0. Do not edit.
// Font: Pico3x5, 3x5, baseline 4, default advance 3, 38 glyphs.
/**
 * Pico3x5 - a 3x5 pixel font exported from Glyphforge.
 * Rows are bit-packed: row y holds the pixels of row y, bit x = column x (LSB first).
 * Glyphs and their advances live in parallel arrays indexed by CODEPOINTS.
 */
object Pico3x5 {
    const val NAME: String = "Pico3x5"
    const val CELL_WIDTH: Int = 3
    const val CELL_HEIGHT: Int = 5
    const val BASELINE: Int = 4
    const val DEFAULT_ADVANCE: Int = 3

    /** Every character this font defines, sorted by code point. */
    val CODEPOINTS: CharArray = charArrayOf(' ', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z')

    /** Row bitmaps, parallel to CODEPOINTS. */
    val ROWS: Array<IntArray> = arrayOf(
        intArrayOf(0x0, 0x0, 0x0, 0x0, 0x0),
        intArrayOf(0x0, 0x0, 0x0, 0x0, 0x2),
        intArrayOf(0x2, 0x5, 0x5, 0x5, 0x2),
        intArrayOf(0x2, 0x3, 0x2, 0x2, 0x2),
        intArrayOf(0x3, 0x4, 0x2, 0x1, 0x3),
        intArrayOf(0x3, 0x4, 0x2, 0x4, 0x3),
        intArrayOf(0x5, 0x5, 0x7, 0x4, 0x4),
        intArrayOf(0x7, 0x1, 0x3, 0x4, 0x3),
        intArrayOf(0x2, 0x1, 0x3, 0x5, 0x2),
        intArrayOf(0x7, 0x4, 0x2, 0x2, 0x2),
        intArrayOf(0x2, 0x5, 0x2, 0x5, 0x2),
        intArrayOf(0x2, 0x5, 0x6, 0x4, 0x2),
        intArrayOf(0x2, 0x5, 0x7, 0x5, 0x5),
        intArrayOf(0x3, 0x5, 0x3, 0x5, 0x3),
        intArrayOf(0x2, 0x5, 0x1, 0x5, 0x2),
        intArrayOf(0x3, 0x5, 0x5, 0x5, 0x3),
        intArrayOf(0x7, 0x1, 0x3, 0x1, 0x7),
        intArrayOf(0x7, 0x1, 0x3, 0x1, 0x1),
        intArrayOf(0x2, 0x5, 0x1, 0x5, 0x6),
        intArrayOf(0x5, 0x5, 0x7, 0x5, 0x5),
        intArrayOf(0x7, 0x2, 0x2, 0x2, 0x7),
        intArrayOf(0x4, 0x4, 0x4, 0x5, 0x2),
        intArrayOf(0x5, 0x5, 0x3, 0x5, 0x5),
        intArrayOf(0x1, 0x1, 0x1, 0x1, 0x7),
        intArrayOf(0x5, 0x7, 0x5, 0x5, 0x5),
        intArrayOf(0x7, 0x5, 0x5, 0x5, 0x5),
        intArrayOf(0x2, 0x5, 0x5, 0x5, 0x2),
        intArrayOf(0x3, 0x5, 0x3, 0x1, 0x1),
        intArrayOf(0x2, 0x5, 0x5, 0x2, 0x4),
        intArrayOf(0x3, 0x5, 0x3, 0x5, 0x5),
        intArrayOf(0x6, 0x1, 0x2, 0x4, 0x3),
        intArrayOf(0x7, 0x2, 0x2, 0x2, 0x2),
        intArrayOf(0x5, 0x5, 0x5, 0x5, 0x2),
        intArrayOf(0x5, 0x5, 0x5, 0x2, 0x2),
        intArrayOf(0x5, 0x5, 0x7, 0x5, 0x5),
        intArrayOf(0x5, 0x5, 0x2, 0x5, 0x5),
        intArrayOf(0x5, 0x5, 0x2, 0x2, 0x2),
        intArrayOf(0x7, 0x4, 0x2, 0x1, 0x7),
    )

    /** Advance widths, parallel to CODEPOINTS. */
    val ADVANCE: IntArray = intArrayOf(3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3)

    /** Kerning pairs, parallel: left char, right char, advance adjustment. */
    val KERN_LEFT: CharArray = charArrayOf('A', 'A', 'A', 'L', 'V')
    val KERN_RIGHT: CharArray = charArrayOf('T', 'V', 'W', 'T', 'A')
    val KERN_AMOUNT: IntArray = intArrayOf(-1, -1, -1, -1, -1)
    fun kern(a: Char, b: Char): Int {
        for (i in KERN_LEFT.indices) if (KERN_LEFT[i] == a && KERN_RIGHT[i] == b) return KERN_AMOUNT[i]
        return 0
    }

    fun index(c: Char): Int {
        for (i in CODEPOINTS.indices) if (CODEPOINTS[i] == c) return i
        return -1
    }

    /** Row bitmaps for [c], or a blank grid when the font does not define it. */
    fun rows(c: Char): IntArray = index(c).let { if (it < 0) IntArray(CELL_HEIGHT) else ROWS[it] }

    /** Advance width for [c], defaulting to DEFAULT_ADVANCE. */
    fun advance(c: Char): Int = index(c).let { if (it < 0) DEFAULT_ADVANCE else ADVANCE[it] }

    fun pixel(c: Char, x: Int, y: Int): Boolean {
        if (x !in 0 until CELL_WIDTH || y !in 0 until CELL_HEIGHT) return false
        return (rows(c)[y] ushr x) and 1 == 1
    }

    /** Renders one glyph as [on]/[off] art. */
    fun render(c: Char, on: Char = '#', off: Char = ' '): List<String> {
        val r = rows(c)
        return (0 until CELL_HEIGHT).map { y ->
            (0 until CELL_WIDTH).joinToString("") { x -> if ((r[y] ushr x) and 1 == 1) on.toString() else off.toString() }
        }
    }

    /** Renders a string, honoring per-glyph advance widths and kerning. */
    fun renderText(text: String, on: Char = '#', off: Char = ' '): List<String> {
        val out = mutableListOf<String>()
        for (line in text.split('\n')) {
            val pos = IntArray(line.length)
            var col = 0
            for (i in line.indices) {
                pos[i] = col
                col += advance(line[i])
                if (i + 1 < line.length) col += kern(line[i], line[i + 1])
            }
            val width = if (line.isEmpty()) 0 else col.coerceAtLeast(1)
            for (y in 0 until CELL_HEIGHT) {
                val grid = CharArray(width) { off }
                for (i in line.indices) {
                    val r = rows(line[i])
                    val a = advance(line[i])
                    for (x in 0 until a) {
                        val idx = pos[i] + x
                        if (idx in 0 until width) grid[idx] = if ((r[y] ushr x) and 1 == 1) on else off
                    }
                }
                out.add(grid.concatToString())
            }
        }
        return out
    }
}
