if(EXISTS "/home/runner/work/RandomLabs/RandomLabs/prism/build-release/prism_tests[1]_tests.cmake")
  include("/home/runner/work/RandomLabs/RandomLabs/prism/build-release/prism_tests[1]_tests.cmake")
else()
  add_test(prism_tests_NOT_BUILT prism_tests_NOT_BUILT)
endif()
