// EBCOT-style bitplane coder with the pinned parent-aware context (I28) plus the
// X3a learned neural context model.
//
// Codec structure: for each subband in coding order (LL first, then HL/LH/HH
// coarse-to-fine), and for each bitplane from MSB down to LSB, each coefficient
// emits one SIGNIFICANCE (or REFINEMENT) bit; on the bitplane where a coefficient
// first becomes significant an extra SIGN bit follows. The probability for every
// symbol is produced by LearnedModel: a per-context EMA (the legacy I28 adaptive
// model) blended with a tiny MLP that turns a window of already-coded neighbour /
// own magnitudes into a data-driven prior. All features are computable from
// already-coded information at both encode and decode time, so the rANS stream
// round-trips exactly and no model table is ever transmitted (invariant I29).

#include "prism/codec/bitplane.h"
#include "prism/codec/bitplane_rans.h"
#include "prism/codec/learned_ctx.h"
#include "route6d_tree.inc" // baked property tree (R6D), generated by `prism train-r6d-tree`
#include <algorithm>
#include <stdexcept>
#include <vector>
#include <cmath>

namespace prism::codec {

namespace {

// X6c hyperprior: apply a per-subband probability-calibration factor `s` to a
// predicted P(0)*M probability. p0 in [1, 65534] keeps rANS valid (P(0),P(1) both
// strictly inside (0, M)). Sub-1 factors sharpen the predicted peak (assume the
// model over-spreads the mass); super-1 factors flatten it. Symmetric encode/decode.
static inline uint16_t scale_p0(uint16_t p, float s) {
    if (s == 1.0f) return p;
    float v = (float)p * s;
    if (v < 1.0f) v = 1.0f;
    if (v > 65534.0f) v = 65534.0f;
    return (uint16_t)std::lround(v);
}

int floor_log2(uint32_t v) {
    if (v == 0) return -1;
    return 31 - __builtin_clz(v);
}

int mag_bucket(int32_t v) {
    if (v <= 0) return 0;
    return (int)std::min(7, floor_log2((uint32_t)v));
}

// R6-B class: (symtype x bitplane-bucket). Both terms are known at BOTH encode
// and decode time BEFORE the bit is decided (symtype is the walk state; p is the
// current bitplane index), so the class is perfectly symmetric and the
// transmitted per-class histogram stays a valid static prior. 3 symtypes x 4
// bitplane buckets = 12 classes (research-route6 section 3).
inline int r6b_class(uint8_t symtype, int p) {
    int pb = (p < 3) ? 0 : (p < 6) ? 1 : (p < 9) ? 2 : 3;
    return (int)symtype * 4 + pb;
}

// R6-B blend model: a transmitted per-(subband, class) static P(0) backbone
// combined with the learned context model (MLP prior + per-context adaptive
// EMA, i.e. LearnedModel). The static histogram is the JXL-Modular "transmitted
// tree" that removes the per-subband systematic bias and seeds every context at
// its class empirical distribution instead of p=0.5; the learned model keeps the
// magnitude-aware prior and refines rich contexts. Both evolve identically at
// encode and decode (the learned weights are baked constants, the static table
// is transmitted), so the rANS stream round-trips byte-exact. R6B_W_STATIC is a
// global blend weight (0 = pure learned, 1 = pure transmitted histogram).
struct StaticAdaptiveModel {
    static constexpr uint32_t M = 1u << 16;
    static constexpr float W_STATIC = 0.35f; // transmitted-histogram weight
    std::vector<std::vector<uint16_t>> sp0;  // [NS][R6B_CLASSES]
    LearnedModel learned;

    void init(size_t NS, const std::vector<std::vector<uint16_t>>& s) {
        sp0 = s;
        learned = LearnedModel();
    }
    uint16_t predict(const LCFeat& f, uint8_t oi, uint8_t cls) const {
        uint16_t lp = learned.predict(f);
        uint16_t sp = sp0[oi][cls];
        float w = W_STATIC;
        int b = (int)(w * (float)sp + (1.0f - w) * (float)lp);
        if (b < 1) b = 1;
        if (b > (int)M - 1) b = (int)M - 1;
        return (uint16_t)b;
    }
    void update(const LCFeat& f, uint8_t bit) { learned.update(f, bit); }
};

// R6-C cluster model: a transmitted per-cluster static P(0) backbone combined
// with the learned context model (MLP prior + per-context adaptive EMA). The
// cluster id is a pure function of the MLP prior (see r6c_cluster), so it is
// identical at encode and decode and the static table stays a valid prior. The
// static histogram removes cold-start for rare fine contexts (which the EMA
// never sees enough symbols to converge) by seeding every cluster at its
// empirical distribution; the learned model keeps the magnitude-aware prior and
// refines rich clusters. Both evolve identically at encode and decode (the
// learned weights are baked constants; the static table is transmitted), so the
// rANS stream round-trips byte-exact.
struct StaticClusterModel {
    static constexpr uint32_t M = 1u << 16;
    static constexpr float W_STATIC = 0.75f; // transmitted-histogram weight
    int NB = 0;
    std::vector<uint16_t> sp0;   // [NB] transmitted P(0)*M
    LearnedModel learned;

    void init(int nb, const std::vector<std::vector<uint32_t>>& cnt) {
        NB = nb;
        learned = LearnedModel();
        sp0.assign(nb, (uint16_t)(M / 2));
        for (int i = 0; i < nb; ++i) {
            uint32_t c0 = cnt[i][0], c1 = cnt[i][1];
            uint32_t tot = c0 + c1;
            sp0[i] = (tot == 0) ? (uint16_t)(M / 2)
                                : (uint16_t)((uint32_t)((uint64_t)c0 * M / tot) & 0xFFFF);
        }
    }
    uint16_t predict(const LCFeat& f, int cluster, uint16_t mlp_p0) const {
        uint16_t lp = learned.predict_with(f, mlp_p0);
        uint16_t sp = (cluster >= 0 && cluster < NB) ? sp0[cluster] : (uint16_t)(M / 2);
        float w = W_STATIC;
        int b = (int)(w * (float)sp + (1.0f - w) * (float)lp);
        if (b < 1) b = 1;
        if (b > (int)M - 1) b = (int)M - 1;
        return (uint16_t)b;
    }
    void update(const LCFeat& f, uint8_t bit) { learned.update(f, bit); }
};

// R6-C cluster id: map a symbol to a learned context cluster. The learned MLP
// P(0) (symmetrically available at both encode and decode) is quantised into
// KB probability buckets; the symtype separates significance / sign /
// refinement so they keep disjoint static histograms. All three terms are
// known before the bit is decided, so the cluster is perfectly symmetric.
inline int r6c_cluster(uint8_t symtype, uint16_t p0, int kb) {
    int bucket = (int)((uint64_t)p0 * (uint32_t)kb / StaticClusterModel::M);
    if (bucket >= kb) bucket = kb - 1;
    return (int)symtype * kb + bucket;
}

// Route 6D (issue #130): read the raw magnitude for a property-tree feature id.
inline int r6d_raw_feat(const R6DRaw& r, int feat) {
    switch (feat) {
        case R6D_FEAT_W:   return r.mW;
        case R6D_FEAT_N:   return r.mN;
        case R6D_FEAT_E:   return r.mE;
        case R6D_FEAT_S:   return r.mS;
        case R6D_FEAT_NW:  return r.mNW;
        case R6D_FEAT_NE:  return r.mNE;
        case R6D_FEAT_SW:  return r.mSW;
        case R6D_FEAT_SE:  return r.mSE;
        case R6D_FEAT_PARENT: return r.mParent;
        case R6D_FEAT_LUMA:   return r.mLuma;
        case R6D_FEAT_OWN:    return r.mOwn;
        case R6D_FEAT_PPOS:   return r.ppos;
        case R6D_FEAT_SYMTYPE: return (int)r.symtype;
        case R6D_FEAT_ORIENT:  return (int)r.orient;
        case R6D_FEAT_LEVEL:   return (int)r.level;
        case R6D_FEAT_PARENT_SIG: return (int)r.parent_sig;
        default: return 0;
    }
}

// Fill the RAW (un-quantised) feature snapshot for the symbol at (x,y) on bitplane
// p, mirroring learned_features exactly but storing RAW magnitudes (not log2
// buckets). The single source of truth so encode / decode / train agree.
inline void r6d_raw_features(const std::vector<uint8_t>& sig,
                             const std::vector<int32_t>& curmag,
                             const std::vector<int32_t>* pmag, int pw, int ph,
                             const std::vector<int32_t>* lmag,
                             int w, int h, int x, int y, int p, int symtype,
                             int orient, int level, int parent_sig, int fc, int dg,
                             R6DRaw& r) {
    (void)fc; (void)dg;
    auto raw_at = [&](int nx, int ny) -> int {
        if (nx >= 0 && nx < w && ny >= 0 && ny < h && sig[(size_t)ny * w + nx])
            return (int)std::abs(curmag[(size_t)ny * w + nx]);
        return 0;
    };
    r.symtype = (uint8_t)symtype;
    r.orient = (uint8_t)orient;
    r.level = (uint8_t)level;
    r.parent_sig = (uint8_t)(parent_sig ? 1 : 0);
    r.mW = raw_at(x - 1, y);
    r.mN = raw_at(x, y - 1);
    r.mE = raw_at(x + 1, y);
    r.mS = raw_at(x, y + 1);
    r.mNW = raw_at(x - 1, y - 1);
    r.mNE = raw_at(x + 1, y - 1);
    r.mSW = raw_at(x - 1, y + 1);
    r.mSE = raw_at(x + 1, y + 1);
    int pm = 0;
    if (pmag) {
        int pcx = x >> 1, pcy = y >> 1;
        if (pcx < pw && pcy < ph) pm = (int)std::abs((*pmag)[(size_t)pcy * pw + pcx]);
    }
    r.mParent = pm;
    int lm = 0;
    if (lmag) lm = (int)std::abs((*lmag)[(size_t)y * w + x]);
    r.mLuma = lm;
    r.mOwn = (int)std::abs(curmag[(size_t)y * w + x]);
    r.ppos = p;
}

// Walk the baked property tree to a leaf id in [0, R6D_K).
inline int r6d_leaf(const R6DRaw& r) {
    int node = 0;
    while (R6D_TREE[node].split != 0) {
        const R6DNode& nd = R6D_TREE[node];
        bool go_rhs;
        if (nd.split == 1) go_rhs = (r6d_raw_feat(r, nd.feat) >= (int)nd.thr);
        else go_rhs = ((int)r.symtype == (int)nd.thr); // categorical symtype
        node = go_rhs ? nd.rhs : nd.lhs;
    }
    return R6D_TREE[node].leaf;
}

// Like r6d_leaf, but defensive: clamps the leaf id into [0, K-1] so the coder is
// robust to any K (the baked tree's max leaf id is R6D_K-1). Encode and decode
// both clamp identically, so round-trip is unaffected.
inline int r6d_leaf_id(const R6DRaw& r, int K) {
    int l = r6d_leaf(r);
    if (l >= K) l = K - 1;
    return l;
}

// R6-D blend model: a transmitted per-leaf (K*3) static P(0) backbone combined
// with the retained adaptive EMA. The leaf is a function of already-coded RAW
// magnitudes only (route6d_tree.inc, baked constant), so encode/decode agree and
// the static table stays a valid prior. At W>=1.0 pure-transmitted is the
// guaranteed no-worse lower bound (each leaf pools >= its own cell's samples).
struct StaticTreeModel {
    static constexpr uint32_t M = 1u << 16;
    float W_STATIC = 0.7f; // transmitted-histogram weight
    int K = 0;
    std::vector<uint16_t> sp0;   // [K*3] transmitted P(0)*M (sign entries neutral)
    LearnedModel learned;
    void init(int k, const std::vector<uint16_t>& s) {
        K = k; sp0 = s; learned = LearnedModel();
    }
    uint16_t predict(const R6DRaw& r, const LCFeat& f) const {
        uint16_t sp = sp0[(size_t)r6d_leaf_id(r, K) * 3 + r.symtype];
        if (W_STATIC >= 1.0f) return sp;
        uint16_t lp = learned.predict(f);
        int b = (int)(W_STATIC * (float)sp + (1.0f - W_STATIC) * (float)lp);
        if (b < 1) b = 1;
        if (b > (int)M - 1) b = (int)M - 1;
        return (uint16_t)b;
    }
    void update(const LCFeat& f, uint8_t bit) { learned.update(f, bit); }
};

// Build the coding order: LL(level 0) first, then level 1..maxlevel HL,LH,HH.
std::vector<int> coding_order(const std::vector<Subband>& subs, int& maxlevel) {
    int ml = 0;
    for (const auto& s : subs) if (s.level > ml) ml = s.level;
    maxlevel = ml;
    std::vector<int> map(4 * (ml + 1), -1);
    for (int i = 0; i < (int)subs.size(); ++i)
        map[(int)subs[i].orient * (ml + 1) + subs[i].level] = i;
    std::vector<int> order;
    order.reserve(subs.size());
    if (map[0 * (ml + 1) + 0] >= 0) order.push_back(map[0 * (ml + 1) + 0]);
    for (int L = 1; L <= ml; ++L)
        for (int o = 1; o <= 3; ++o) {
            int idx = map[o * (ml + 1) + L];
            if (idx >= 0) order.push_back(idx);
        }
    return order;
}

std::vector<int> build_parent_map(const std::vector<Subband>& subs, int ml) {
    std::vector<int> map(4 * (ml + 1), -1);
    for (int i = 0; i < (int)subs.size(); ++i)
        map[(int)subs[i].orient * (ml + 1) + subs[i].level] = i;
    std::vector<int> parent(subs.size(), -1);
    for (int i = 0; i < (int)subs.size(); ++i) {
        const Subband& s = subs[i];
        if (s.level == 0) parent[i] = -1;
        else if (s.level == 1) parent[i] = map[0 * (ml + 1) + 0];
        else parent[i] = map[(int)s.orient * (ml + 1) + (s.level - 1)];
    }
    return parent;
}

// 8-neighbour significance pattern -> (fc, dg) counts (EBCOT significance
// propagation context, the legacy I28 base).
void neighbor_counts(const std::vector<uint8_t>& sig, int w, int h, int x, int y,
                     int& fc, int& dg) {
    fc = 0; dg = 0;
    auto at = [&](int nx, int ny) -> bool {
        return nx >= 0 && nx < w && ny >= 0 && ny < h && sig[(size_t)ny * w + nx];
    };
    if (at(x - 1, y)) ++fc;
    if (at(x + 1, y)) ++fc;
    if (at(x, y - 1)) ++fc;
    if (at(x, y + 1)) ++fc;
    if (at(x - 1, y - 1)) ++dg;
    if (at(x + 1, y - 1)) ++dg;
    if (at(x - 1, y + 1)) ++dg;
    if (at(x + 1, y + 1)) ++dg;
}

// R6-A: Build a mapping from subband index to its sibling subband index.
// Siblings are LH(1)<->HL(2) at the same level. LL(0) and HH(3) have no sibling (-1).
std::vector<int> build_sibling_map(const std::vector<Subband>& subbands) {
    size_t NS = subbands.size();
    std::vector<int> sibling(NS, -1);
    for (size_t i = 0; i < NS; ++i) {
        for (size_t j = i + 1; j < NS; ++j) {
            if (subbands[i].level == subbands[j].level) {
                int oi = (int)subbands[i].orient, oj = (int)subbands[j].orient;
                if ((oi == 1 && oj == 2) || (oi == 2 && oj == 1)) {
                    sibling[i] = (int)j;
                    sibling[j] = (int)i;
                }
            }
        }
    }
    return sibling;
}

// Compute the learned features for the symbol at (x, y) on bitplane p within
// subband `si`. `sig`/`mag` are the single-subband significance and RUNNING
// reconstructed-magnitude maps (already-coded coefficients only). `pmag` (when
// non-null) is the parent subband's magnitude map. `lmag`/`lsig` (when non-null)
// are the co-located LUMA subband's magnitude/significance maps (X5a cross-
// component context); indexed by the SAME oi as the subband being coded.
// Identical between encoder and decoder because both maintain `mag`/`sig` from
// the same already-coded state.
//
// R6-A: two new features (sibling-orientation magnitude, parent bitplane lag)
// appended after the base 13.
void learned_features(const std::vector<uint8_t>& sig,
                      const std::vector<int32_t>& mag,
                      const std::vector<int32_t>* pmag, int pw, int ph,
                      const std::vector<int32_t>* lmag,
                      int w, int h, int x, int y, int p, int symtype,
                      int level, LCFeat& f,
                      const std::vector<int32_t>* sib_mag = nullptr,
                      int parent_topbit = -1,
                      int sib_w = 0, int sib_h = 0) {
    int nm = 0;
    auto nmag_at = [&](int nx, int ny) {
        if (nx >= 0 && nx < w && ny >= 0 && ny < h && sig[(size_t)ny * w + nx])
            nm = std::max(nm, (int)mag[(size_t)ny * w + nx]);
    };
    nmag_at(x - 1, y); nmag_at(x + 1, y); nmag_at(x, y - 1); nmag_at(x, y + 1);
    nmag_at(x - 1, y - 1); nmag_at(x + 1, y - 1); nmag_at(x - 1, y + 1); nmag_at(x + 1, y + 1);
    int pm = 0;
    if (pmag) {
        int pcx = x >> 1, pcy = y >> 1;
        if (pcx < pw && pcy < ph) pm = (int)(*pmag)[(size_t)pcy * pw + pcx];
    }
    int lm = 0, ls = 0;
    if (lmag) lm = (int)std::abs((*lmag)[(size_t)y * w + x]), ls = ((*lmag)[(size_t)y * w + x] != 0);
    uint8_t nmag = (uint8_t)mag_bucket(nm);
    uint8_t pmag_b = (uint8_t)mag_bucket(pm);
    uint8_t ownmag = 0;
    if (symtype == 1) ownmag = (uint8_t)std::min(7, p);                   // sign: msb == p
    else if (symtype == 2) ownmag = (uint8_t)mag_bucket(mag[(size_t)y * w + x]); // refine
    // R6-A F7: sibling-orientation magnitude (HL<->LH correlation).
    uint8_t sib_m = 0;
    if (sib_mag && sib_w > 0 && sib_h > 0) {
        if (x >= 0 && x < sib_w && y >= 0 && y < sib_h) {
            int32_t sm = (*sib_mag)[(size_t)y * sib_w + x];
            if (sm != 0) sib_m = (uint8_t)mag_bucket(sm);
        }
    }
    // R6-A F8: parent-child bitplane lag (autocorrelation).
    uint8_t pplag = 0;
    if (parent_topbit >= 0 && parent_topbit > p)
        pplag = (uint8_t)std::min(7, parent_topbit - p);

    f = make_lcfeat((uint8_t)symtype, 0, 0, 0, 0, nmag, pmag_b, ownmag, (uint8_t)std::min(7, p),
                    (uint8_t)std::min(5, level), (uint8_t)mag_bucket(lm),
                    (uint8_t)(ls ? 1 : 0), sib_m, pplag);
}

} // namespace

// R9: build the raw already-coded magnitude snapshot `r` for the symbol at
// (x,y) on bitplane p, used to key the fixed tree-quantized EMA. Mirrors the
// argument list of learned_features so the two stay in lock-step.
inline R6DRaw make_r6d_raw(const std::vector<uint8_t>& sig,
                           const std::vector<int32_t>& curmag,
                           const std::vector<int32_t>* pmag, int pw, int ph,
                           const std::vector<int32_t>* lmag,
                           int w, int h, int x, int y, int p, int symtype,
                           int orient, int level, int parent_sig, int fc, int dg) {
    R6DRaw r;
    r6d_raw_features(sig, curmag, pmag, pw, ph, lmag, w, h, x, y, p, symtype,
                     orient, level, parent_sig, fc, dg, r);
    return r;
}

uint32_t BitplaneCoder::context_id(Subband::Orient o, bool parent_sig, int fc, int dg) {
    uint32_t orient = (uint32_t)o;          // 0..3  (2 bits)
    uint32_t ps = parent_sig ? 1u : 0u;     // 1 bit
    uint32_t f = (fc > 4) ? 4u : (uint32_t)fc;  // 0..4 (3 bits)
    uint32_t d = (dg > 4) ? 4u : (uint32_t)dg;  // 0..4 (3 bits)
    return orient + ps * 4u + f * 8u + d * 40u; // base in [0, 199]
}

static inline uint32_t coarse_ctx(uint32_t base, int symtype) {
    return base + (uint32_t)symtype * 200u; // 0..199 sig, 200..399 sign, 400..599 refine
}

BitplaneCoder::Result BitplaneCoder::encode(const std::vector<Subband>& subbands,
                                            int maxbits_override,
                                            const std::vector<std::vector<int32_t>>* luma_mag,
                                            const std::vector<float>* sub_scale) const {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    auto sibling = build_sibling_map(subbands);
    size_t NS = subbands.size();

    // Per-subband bitplane range (EBCOT-style): each subband keeps its own B so
    // tiny AC bands are not forced to emit the global LL bit-depth as wasted
    // all-zero significance bits. Indexed by original subband index oi.
    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }

    // Shared per-subband state, indexed by original oi. Shared so a child
    // subband's PARENT magnitude/context is available while it is coded (the
    // critical X3b fix: previously each subband was encoded in isolation, so
    // parent features were always zero at inference).
    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS), curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0);
        magv[oi].resize(n);
        curmag[oi].assign(n, 0);
        sgn[oi].resize(n);
        topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m;
            sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }

    uint32_t total = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        int B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        total += (uint32_t)(n * (size_t)B);
        for (size_t ci = 0; ci < n; ++ci)
            if (magv[oi][ci] > 0) ++total;
    }

    std::vector<std::vector<uint8_t>> streams(NS);
    // One shared predictor across the whole plane so the EMA branch evolves the
    // same way it did during training (collect_samples walks all subbands of a
    // plane with a single persistent model). Encode and decode both share one
    // model per plane, so roundtrip stays byte-exact.
    LearnedModel model;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        float sc = (sub_scale && oi < sub_scale->size()) ? (*sub_scale)[oi] : 1.0f;
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        int sib_idx = sibling[oi];
        const std::vector<int32_t>* sib_mag_ptr = (sib_idx >= 0) ? &curmag[sib_idx] : nullptr;
        int sib_w = (sib_idx >= 0) ? subbands[sib_idx].w : 0;
        int sib_h = (sib_idx >= 0) ? subbands[sib_idx].h : 0;
        std::vector<uint8_t> bits;
        std::vector<uint16_t> p0;
        bits.reserve(n * (size_t)B + n);
        p0.reserve(n * (size_t)B + n);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                int ptb = -1;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph) {
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                        ptb = (curmag[pidx][(size_t)pcy * pw + pcx] != 0)
                            ? floor_log2((uint32_t)curmag[pidx][(size_t)pcy * pw + pcx])
                            : -1;
                    }
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    uint8_t bit = becomes ? 1 : 0;
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, s.level, f, sib_mag_ptr, ptb, sib_w, sib_h);
                     f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                     R6DRaw _r = make_r6d_raw(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, (int)s.orient, s.level, parent_sig, fc, dg);
                     p0.push_back(scale_p0(model.predict(f, _r), sc)); bits.push_back(bit); model.update(f, _r, bit);
                     if (becomes) {
                        uint8_t sg = sgn[oi][ci];
                        LCFeat fs; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, s.level, fs, sib_mag_ptr, ptb, sib_w, sib_h);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        R6DRaw _r = make_r6d_raw(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, (int)s.orient, s.level, parent_sig, fc, dg);
                        p0.push_back(scale_p0(model.predict(fs, _r), sc)); bits.push_back(sg); model.update(fs, _r, sg);
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                     }
                } else {
                    uint8_t bit = (uint8_t)((magv[oi][ci] >> p) & 1);
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, s.level, f, sib_mag_ptr, ptb, sib_w, sib_h);
                     f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                     R6DRaw _r = make_r6d_raw(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, (int)s.orient, s.level, parent_sig, fc, dg);
                     p0.push_back(scale_p0(model.predict(f, _r), sc)); bits.push_back(bit); model.update(f, _r, bit);
                     if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
        BitplaneRans rans;
        streams[oi] = rans.encode(bits, p0);
    }

    Result res;
    res.streams = std::move(streams);
    res.sub_maxbits = std::move(sub_maxbits);
    res.total_symbols = total;
    return res;
}


std::vector<Subband> BitplaneCoder::decode(const std::vector<std::vector<uint8_t>>& streams,
                                            const std::vector<Subband>& layout,
                                            const std::vector<uint8_t>& sub_maxbits,
                                            uint32_t total_symbols,
                                            const std::vector<std::vector<int32_t>>* luma_mag,
                                            const std::vector<float>* sub_scale) const {
    int ml = 0;
    auto order = coding_order(layout, ml);
    auto parent = build_parent_map(layout, ml);
    auto sibling = build_sibling_map(layout);
    size_t NS = layout.size();

    std::vector<Subband> out = layout;
    for (auto& s : out) s.coeffs.assign((size_t)s.w * s.h, 0);

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> value(NS);
    std::vector<std::vector<int8_t>> signv(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        sig[oi].assign(n, 0); value[oi].resize(n, 0); signv[oi].assign(n, 1);
    }

    uint32_t idx = 0;
    // One shared predictor per plane (matches encode and training EMA evolution).
    LearnedModel model;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = layout[oi];
        float sc = (sub_scale && oi < sub_scale->size()) ? (*sub_scale)[oi] : 1.0f;
        int w = s.w, h = s.h;
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? layout[pidx].w : 0, ph = (pidx >= 0) ? layout[pidx].h : 0;
        int si_idx = sibling[oi];
        const std::vector<int32_t>* sib_val_ptr = (si_idx >= 0) ? &value[si_idx] : nullptr;
        int sib_w = (si_idx >= 0) ? layout[si_idx].w : 0;
        int sib_h = (si_idx >= 0) ? layout[si_idx].h : 0;
        int B = sub_maxbits[oi];
        BitplaneRans::Decoder d; d.init(streams[oi]);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < s.coeffs.size(); ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                int ptb = -1;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph) {
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                        ptb = (value[pidx][(size_t)pcy * pw + pcx] != 0) ? floor_log2((uint32_t)std::abs(value[pidx][(size_t)pcy * pw + pcx])) : -1;
                    }
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                if (sig[oi][ci] == 0) {
                    LCFeat f; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, s.level, f, sib_val_ptr, ptb, sib_w, sib_h);
                     f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                     R6DRaw _r = make_r6d_raw(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, (int)s.orient, s.level, parent_sig, fc, dg);
                     uint8_t bit = d.decode_symbol(scale_p0(model.predict(f, _r), sc)); model.update(f, _r, bit); ++idx;
                     if (bit) {
                        LCFeat fs; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, s.level, fs, sib_val_ptr, ptb, sib_w, sib_h);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        R6DRaw _r = make_r6d_raw(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, (int)s.orient, s.level, parent_sig, fc, dg);
                        uint8_t sg = d.decode_symbol(scale_p0(model.predict(fs, _r), sc)); model.update(fs, _r, sg); ++idx;
                        sig[oi][ci] = 1; signv[oi][ci] = sg ? -1 : 1;
                        value[oi][ci] = (int32_t)(1 << p);
                     }
                } else {
                    LCFeat f; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, s.level, f, sib_val_ptr, ptb, sib_w, sib_h);
                     f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                     R6DRaw _r = make_r6d_raw(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, (int)s.orient, s.level, parent_sig, fc, dg);
                     uint8_t rb = d.decode_symbol(scale_p0(model.predict(f, _r), sc)); model.update(f, _r, rb); ++idx;
                     if (rb) value[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }

    if (total_symbols != 0 && idx != total_symbols)
        throw std::runtime_error("BitplaneCoder::decode: symbol count mismatch");

    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        for (size_t ci = 0; ci < n; ++ci)
            out[oi].coeffs[ci] = (int32_t)value[oi][ci] * signv[oi][ci];
    }
    return out;
}

std::pair<std::vector<uint8_t>, std::vector<uint16_t>>
BitplaneCoder::generate_symbols(const std::vector<Subband>& subbands, int maxbits_override,
                                const std::vector<std::vector<int32_t>>* luma_mag,
                                const std::vector<float>* sub_scale) {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    auto sibling = build_sibling_map(subbands);
    size_t NS = subbands.size();

    // Per-subband bitplane range, mirroring encode()/decode() (F2): previously a
    // single global B forced tiny AC bands to emit wasted all-zero significance
    // planes that encode/decode never produce. Indexed by original subband oi.
    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }
    // Shared per-subband state indexed by original oi (F2b).
    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS);
    std::vector<std::vector<int32_t>> curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0); magv[oi].resize(n); curmag[oi].assign(n, 0);
        sgn[oi].resize(n); topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m; sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }
    std::vector<uint8_t> bits; std::vector<uint16_t> p0;
    LearnedModel model;
    for (size_t si = 0; si < order.size(); ++si) {
        int oi = order[si]; const Subband& s = subbands[oi];
        float sc = (sub_scale && oi < sub_scale->size()) ? (*sub_scale)[oi] : 1.0f;
        int w = s.w, h = s.h; int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0, ph = (pidx >= 0) ? subbands[pidx].h : 0;
        int si_idx = sibling[oi];
        const std::vector<int32_t>* sib_mag_ptr = (si_idx >= 0) ? &curmag[si_idx] : nullptr;
        int sib_w = (si_idx >= 0) ? subbands[si_idx].w : 0;
        int sib_h = (si_idx >= 0) ? subbands[si_idx].h : 0;
        int B = sub_maxbits[oi];
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < s.coeffs.size(); ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                int ptb = -1;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph) {
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                        ptb = (curmag[pidx][(size_t)pcy * pw + pcx] != 0)
                            ? floor_log2((uint32_t)curmag[pidx][(size_t)pcy * pw + pcx])
                            : -1;
                    }
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    uint8_t bit = becomes ? 1 : 0;
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, s.level, f, sib_mag_ptr, ptb, sib_w, sib_h);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc=(uint8_t)fc; f.dg=(uint8_t)dg;
                    p0.push_back(scale_p0(model.predict(f), sc)); bits.push_back(bit); model.update(f, bit);
                    if (becomes) {
                        uint8_t sg = sgn[oi][ci];
                        LCFeat fs; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, s.level, fs, sib_mag_ptr, ptb, sib_w, sib_h);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc=(uint8_t)fc; fs.dg=(uint8_t)dg;
                        p0.push_back(scale_p0(model.predict(fs), sc)); bits.push_back(sg); model.update(fs, sg);
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    uint8_t bit = (uint8_t)((magv[oi][ci] >> p) & 1);
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, s.level, f, sib_mag_ptr, ptb, sib_w, sib_h);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc=(uint8_t)fc; f.dg=(uint8_t)dg;
                    p0.push_back(scale_p0(model.predict(f), sc)); bits.push_back(bit); model.update(f, bit);
                    if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }
    return {bits, p0};
}

bool BitplaneCoder::probe_rans(const std::vector<Subband>& subbands, int maxbits_override) {
    auto [bits, p0] = generate_symbols(subbands, maxbits_override);
    BitplaneRans r;
    auto enc = r.encode(bits, p0);
    BitplaneRans::Decoder d; d.init(enc);
    std::vector<uint8_t> out(bits.size(), 0);
    for (uint32_t k = 0; k < bits.size(); ++k) out[k] = d.decode_symbol(p0[k]);
    return out == bits;
}

void BitplaneCoder::collect_samples(const std::vector<Subband>& subbands,
                                    std::vector<LSample>& out, int maxbits_override,
                                    const std::vector<std::vector<int32_t>>* luma_mag,
                                    const std::vector<float>* sub_scale) {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    auto sibling = build_sibling_map(subbands);
    size_t NS = subbands.size();
    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }

    // Shared per-subband state indexed by ORIGINAL subband index oi, exactly like
    // encode()/decode() (F2b: previously indexed by coding-order si, which made
    // the parent lookup sig[pidx] (an oi) read the wrong subband's map).
    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS);
    std::vector<std::vector<int32_t>> curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0); magv[oi].resize(n); curmag[oi].assign(n, 0);
        sgn[oi].resize(n); topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m; sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }
    for (size_t si = 0; si < order.size(); ++si) {
        int oi = order[si]; const Subband& s = subbands[oi];
        int w = s.w, h = s.h; int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0, ph = (pidx >= 0) ? subbands[pidx].h : 0;
        int B = sub_maxbits[oi];
        int sib_idx = sibling[oi];
        const std::vector<int32_t>* sib_mag_ptr = (sib_idx >= 0) ? &curmag[sib_idx] : nullptr;
        int sib_w = (sib_idx >= 0) ? subbands[sib_idx].w : 0;
        int sib_h = (sib_idx >= 0) ? subbands[sib_idx].h : 0;
        for (int p = B - 1; p >= 0; --p) {
            for (int ci = 0; ci < (int)s.coeffs.size(); ++ci) {
                int x = ci % w, y = ci / w;
                bool parent_sig = false;
                int ptb = -1;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph) {
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                        ptb = (curmag[pidx][(size_t)pcy * pw + pcx] != 0)
                            ? floor_log2((uint32_t)curmag[pidx][(size_t)pcy * pw + pcx])
                            : -1;
                    }
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                uint32_t base = context_id(s.orient, parent_sig, fc, dg);
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, s.level, f, sib_mag_ptr, ptb, sib_w, sib_h);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc=(uint8_t)fc; f.dg=(uint8_t)dg;
                    out.push_back({f, becomes ? 1 : 0, coarse_ctx(base, 0)});
                    if (becomes) {
                        LCFeat fs; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, s.level, fs, sib_mag_ptr, ptb, sib_w, sib_h);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc=(uint8_t)fc; fs.dg=(uint8_t)dg;
                        out.push_back({fs, sgn[oi][ci], coarse_ctx(base, 1)});
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    uint8_t bit = (uint8_t)((magv[oi][ci] >> p) & 1);
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, s.level, f, sib_mag_ptr, ptb, sib_w, sib_h);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc=(uint8_t)fc; f.dg=(uint8_t)dg;
                    out.push_back({f, bit, coarse_ctx(base, 2)});
                    if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }
}

StaticBitplaneResult BitplaneCoder::encode_static(
    const std::vector<Subband>& subbands, int maxbits_override,
    const std::vector<std::vector<int32_t>>* luma_mag) const {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    size_t NS = subbands.size();

    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS), curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0); magv[oi].resize(n); curmag[oi].assign(n, 0);
        sgn[oi].resize(n); topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m; sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }

    // Histogram + symbol stores (pass 1). We accumulate per-(subband, class)
    // counts and remember each symbol's bit so pass 2 can blend the transmitted
    // static backbone with the learned model (re-walking for the LCFeat) and
    // rANS-encode.
    StaticHist hist;
    hist.cnt.assign(NS, std::vector<uint32_t>(R6B_CLASSES * 2, 0));
    std::vector<std::vector<uint8_t>> bits_by_sub(NS);
    uint32_t total = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        int B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        total += (uint32_t)(n * (size_t)B);
        for (size_t ci = 0; ci < n; ++ci)
            if (magv[oi][ci] > 0) ++total;
    }
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                uint8_t bit; uint8_t symtype;
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    bit = becomes ? 1 : 0; symtype = 0;
                    int cls = r6b_class(0, p);
                    hist.cnt[oi][cls * 2 + bit]++;
                    bits_by_sub[oi].push_back(bit);
                    if (becomes) {
                        uint8_t sg = sgn[oi][ci]; symtype = 1;
                        int cls = r6b_class(1, p);
                        hist.cnt[oi][cls * 2 + sg]++;
                        bits_by_sub[oi].push_back(sg);
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    bit = (uint8_t)((magv[oi][ci] >> p) & 1); symtype = 2;
                    int cls = r6b_class(2, p);
                    hist.cnt[oi][cls * 2 + bit]++;
                    bits_by_sub[oi].push_back(bit);
                    if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
                (void)symtype;
            }
        }
    }

    // Wire-representability clamp (issue #130, complements the NOTE below):
    // clamp the stored histogram itself so the returned res.hist is exactly
    // what the wire carries (16-bit per count). This makes the container-side
    // clamp a no-op and guarantees any future res.hist consumer sees
    // wire-exact counts. Small images (no count above 65535) are unaffected.
    for (size_t oi = 0; oi < NS; ++oi)
        for (uint32_t& c : hist.cnt[oi])
            if (c > 0xFFFFu) c = 0xFFFFu;

    // Build the transmitted static P(0)*M per (subband, class).
    // NOTE (issue #130, 2026-09-03): the container clamps histogram counts to
    // 16 bits on the wire, so the decoder rebuilds P(0) from CLAMPED counts.
    // The encoder must derive its backbone from the same clamped counts;
    // using raw counts desyncs the rANS stream on images where any class count
    // exceeds 65535 (every real Kodak image) while staying green on small
    // synthetic unit-test images.
    std::vector<std::vector<uint16_t>> sp0(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        sp0[oi].resize(R6B_CLASSES);
        for (int cls = 0; cls < R6B_CLASSES; ++cls) {
            uint32_t c0 = hist.cnt[oi][cls * 2 + 0];
            uint32_t c1 = hist.cnt[oi][cls * 2 + 1];
            if (c0 > 0xFFFF) c0 = 0xFFFF;
            if (c1 > 0xFFFF) c1 = 0xFFFF;
            uint32_t tot = c0 + c1;
            sp0[oi][cls] = (tot == 0) ? (uint16_t)(StaticAdaptiveModel::M / 2)
                                      : (uint16_t)((uint32_t)((uint64_t)c0 * StaticAdaptiveModel::M / tot) & 0xFFFF);
        }
    }

    // Pass 2: blend the transmitted static backbone with the learned model and
    // rANS-encode. We re-walk the coefficients (deterministic) so each symbol's
    // LCFeat + class is recomputed exactly as in pass 1 / decode, and the stored
    // bits (from pass 1) drive the rANS stream. The learned model's EMA evolves
    // identically to decode, so round-trip is byte-exact. Fresh per-subband walk
    // state (lsig/lcurmag) is used so the walk starts from scratch.
    std::vector<std::vector<uint8_t>> streams(NS);
    // Fresh per-subband walk state for the re-walk (must track parent subbands).
    std::vector<std::vector<uint8_t>> lsig(NS);
    std::vector<std::vector<int32_t>> lcurmag(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        lsig[oi].assign(n, 0);
        lcurmag[oi].assign(n, 0);
    }
    StaticAdaptiveModel model; model.init(NS, sp0);
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        const auto& bits = bits_by_sub[oi];
        size_t k = 0;
        std::vector<uint16_t> p0vec;
        p0vec.reserve(bits.size());
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = lsig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(lsig[oi], w, h, x, y, fc, dg);
                const std::vector<int32_t>* parent_cur = (pidx >= 0) ? &lcurmag[pidx] : nullptr;
                const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
                if (lsig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    uint8_t bit = bits[k++];
                    LCFeat f; learned_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 0, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    int cls = r6b_class(0, p);
                    p0vec.push_back(model.predict(f, (uint8_t)oi, (uint8_t)cls));
                    model.update(f, bit);
                    if (becomes) {
                        uint8_t sg = bits[k++];
                        LCFeat fs; learned_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        int cls = r6b_class(1, p);
                        p0vec.push_back(model.predict(fs, (uint8_t)oi, (uint8_t)cls));
                        model.update(fs, sg);
                        lsig[oi][ci] = 1; lcurmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    uint8_t bit = bits[k++];
                    LCFeat f; learned_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 2, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    int cls = r6b_class(2, p);
                    p0vec.push_back(model.predict(f, (uint8_t)oi, (uint8_t)cls));
                    model.update(f, bit);
                    if (bit) lcurmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
        BitplaneRans rans;
        streams[oi] = rans.encode(bits, p0vec);
    }

    StaticBitplaneResult res;
    res.streams = std::move(streams);
    res.sub_maxbits = std::move(sub_maxbits);
    res.total_symbols = total;
    res.hist = std::move(hist);
    return res;
}

std::vector<Subband> BitplaneCoder::decode_static(
    const std::vector<std::vector<uint8_t>>& streams,
    const std::vector<Subband>& layout,
    const std::vector<uint8_t>& sub_maxbits,
    uint32_t total_symbols,
    const StaticHist& hist,
    const std::vector<std::vector<int32_t>>* luma_mag) const {
    int ml = 0;
    auto order = coding_order(layout, ml);
    auto parent = build_parent_map(layout, ml);
    size_t NS = layout.size();

    std::vector<Subband> out = layout;
    for (auto& s : out) s.coeffs.assign((size_t)s.w * s.h, 0);

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> value(NS);
    std::vector<std::vector<int8_t>> signv(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        sig[oi].assign(n, 0); value[oi].resize(n, 0); signv[oi].assign(n, 1);
    }

    // Rebuild the transmitted static P(0)*M per (subband, class).
    std::vector<std::vector<uint16_t>> sp0(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        sp0[oi].resize(R6B_CLASSES);
        for (int cls = 0; cls < R6B_CLASSES; ++cls) {
            uint32_t c0 = hist.cnt[oi][cls * 2 + 0];
            uint32_t c1 = hist.cnt[oi][cls * 2 + 1];
            uint32_t tot = c0 + c1;
            sp0[oi][cls] = (tot == 0) ? (uint16_t)(StaticAdaptiveModel::M / 2)
                                      : (uint16_t)((uint32_t)((uint64_t)c0 * StaticAdaptiveModel::M / tot) & 0xFFFF);
        }
    }

    uint32_t idx = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = layout[oi];
        int w = s.w, h = s.h;
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? layout[pidx].w : 0, ph = (pidx >= 0) ? layout[pidx].h : 0;
        int B = sub_maxbits[oi];
        // Per-subband model reset. This is intentional: the learned feature
        // carried into model.predict/update already includes orient + level
        // (see LearnedModel::fine_ctx), so subband contexts are disjoint; the
        // shared vs per-subband reset choice is benign but kept per-subband for
        // a fully deterministic, symmetric encode/decode accumulator.
        StaticAdaptiveModel model; model.init(NS, sp0);
        BitplaneRans::Decoder d; d.init(streams[oi]);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < s.coeffs.size(); ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                if (sig[oi][ci] == 0) {
                    LCFeat f; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 0, s.level, f);
                f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                int cls = r6b_class(0, p);
                    uint16_t dp0 = model.predict(f, (uint8_t)oi, (uint8_t)cls);
                    uint8_t bit = d.decode_symbol(dp0);
                    model.update(f, bit); ++idx;
                    if (bit) {
                        LCFeat fs; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        int cls = r6b_class(1, p);
                        uint16_t dp0s = model.predict(fs, (uint8_t)oi, (uint8_t)cls);
                        uint8_t sg = d.decode_symbol(dp0s);
                        model.update(fs, sg); ++idx;
                        sig[oi][ci] = 1; signv[oi][ci] = sg ? -1 : 1;
                        value[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    LCFeat f; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, (luma_mag ? &(*luma_mag)[oi] : nullptr), w, h, x, y, p, 2, s.level, f);
                f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                int cls = r6b_class(2, p);
                    uint16_t dp0r = model.predict(f, (uint8_t)oi, (uint8_t)cls);
                    uint8_t rb = d.decode_symbol(dp0r);
                    model.update(f, rb); ++idx;
                    if (rb) value[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }

    if (total_symbols != 0 && idx != total_symbols)
        throw std::runtime_error("BitplaneCoder::decode_static: symbol count mismatch");

    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        for (size_t ci = 0; ci < n; ++ci)
            out[oi].coeffs[ci] = (int32_t)value[oi][ci] * signv[oi][ci];
    }
    return out;
}

StaticClusterBitplaneResult BitplaneCoder::encode_static_cluster(
    const std::vector<Subband>& subbands, int kb, int maxbits_override,
    const std::vector<std::vector<int32_t>>* luma_mag) const {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    size_t NS = subbands.size();
    int NB = 3 * kb;

    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS), curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0); magv[oi].resize(n); curmag[oi].assign(n, 0);
        sgn[oi].resize(n); topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m; sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }

    // Pass 1: walk and accumulate per-cluster counts. The cluster id is derived
    // from the learned MLP prior (a baked constant, symmetric at decode). We
    // only READ the prior here (no EMA update), so pass 2 starts the adaptive
    // model fresh and evolves it identically to decode.
    StaticClusterHist hist;
    hist.kb = kb;
    hist.cnt.assign(NB, std::vector<uint32_t>(2, 0));
    std::vector<std::vector<uint8_t>> bits_by_sub(NS);
    uint32_t total = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        int B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        total += (uint32_t)(n * (size_t)B);
        for (size_t ci = 0; ci < n; ++ci)
            if (magv[oi][ci] > 0) ++total;
    }
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                uint8_t bit;
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    bit = becomes ? 1 : 0;
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 0, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    // MLP prior is computed once per symbol (at the significance
                    // bit, where the own magnitude is still 0) and reused for the
                    // sign and every refinement bit so the cluster id stays a
                    // per-symbol constant. Symmetric at encode/decode.
                    uint16_t mlp0 = learned_predict_p0(f);
                    int cluster = r6c_cluster(0, mlp0, kb);
                    hist.cnt[cluster][bit]++;
                    bits_by_sub[oi].push_back(bit);
                    if (becomes) {
                        uint8_t sg = sgn[oi][ci];
                        LCFeat fs; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        int csg = r6c_cluster(1, mlp0, kb);
                        hist.cnt[csg][sg]++;
                        bits_by_sub[oi].push_back(sg);
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    bit = (uint8_t)((magv[oi][ci] >> p) & 1);
                    LCFeat f; learned_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 2, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t mlp0 = learned_predict_p0(f);
                    int cluster = r6c_cluster(2, mlp0, kb);
                    hist.cnt[cluster][bit]++;
                    bits_by_sub[oi].push_back(bit);
                    if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }

    // Build the transmitted static P(0)*M per cluster.
    std::vector<std::vector<uint32_t>> cnt2 = hist.cnt;

    // Pass 2: re-walk, blend the transmitted cluster backbone with the learned
    // model, rANS-encode. Fresh per-subband walk state (lsig/lcurmag).
    std::vector<std::vector<uint8_t>> streams(NS);
    std::vector<std::vector<uint8_t>> lsig(NS);
    std::vector<std::vector<int32_t>> lcurmag(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        lsig[oi].assign(n, 0);
        lcurmag[oi].assign(n, 0);
    }
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        // Per-subband model reset so the adaptive EMA evolves IDENTICALLY to
        // decode (which also resets per subband). The cluster id depends on the
        // EMA-containing learned prior, so any cross-subband EMA carry-in would
        // desync the cluster and break byte-exact round-trip.
        StaticClusterModel model; model.init(NB, cnt2);
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        const auto& bits = bits_by_sub[oi];
        size_t k = 0;
        std::vector<uint16_t> p0vec;
        p0vec.reserve(bits.size());
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = lsig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(lsig[oi], w, h, x, y, fc, dg);
                const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
                if (lsig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    uint8_t bit = bits[k++];
                    LCFeat f; learned_features(lsig[oi], lcurmag[oi], (pidx>=0?&lcurmag[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 0, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t mlp0 = learned_predict_p0(f);
                    int cluster = r6c_cluster(0, mlp0, kb);
                    p0vec.push_back(model.predict(f, cluster, mlp0));
                    model.update(f, bit);
                    if (becomes) {
                        uint8_t sg = bits[k++];
                        LCFeat fs; learned_features(lsig[oi], lcurmag[oi], (pidx>=0?&lcurmag[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        int csg = r6c_cluster(1, mlp0, kb);
                        p0vec.push_back(model.predict(fs, csg, mlp0));
                        model.update(fs, sg);
                        lsig[oi][ci] = 1; lcurmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    uint8_t bit = bits[k++];
                    LCFeat f; learned_features(lsig[oi], lcurmag[oi], (pidx>=0?&lcurmag[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 2, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t mlp0 = learned_predict_p0(f);
                    int cluster = r6c_cluster(2, mlp0, kb);
                    p0vec.push_back(model.predict(f, cluster, mlp0));
                    model.update(f, bit);
                    if (bit) lcurmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
        BitplaneRans rans;
        streams[oi] = rans.encode(bits, p0vec);
    }

    StaticClusterBitplaneResult res;
    res.streams = std::move(streams);
    res.sub_maxbits = std::move(sub_maxbits);
    res.total_symbols = total;
    res.hist = std::move(hist);
    return res;
}

std::vector<Subband> BitplaneCoder::decode_static_cluster(
    const std::vector<std::vector<uint8_t>>& streams,
    const std::vector<Subband>& layout,
    const std::vector<uint8_t>& sub_maxbits,
    uint32_t total_symbols,
    const StaticClusterHist& hist,
    const std::vector<std::vector<int32_t>>* luma_mag) const {
    int ml = 0;
    auto order = coding_order(layout, ml);
    auto parent = build_parent_map(layout, ml);
    size_t NS = layout.size();
    int kb = hist.kb;
    int NB = 3 * kb;

    std::vector<Subband> out = layout;
    for (auto& s : out) s.coeffs.assign((size_t)s.w * s.h, 0);

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> value(NS);
    std::vector<std::vector<int8_t>> signv(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        sig[oi].assign(n, 0); value[oi].resize(n, 0); signv[oi].assign(n, 1);
    }

    // Rebuild the transmitted static P(0)*M per cluster.
    std::vector<std::vector<uint32_t>> cnt(NB, std::vector<uint32_t>(2, 0));
    for (int i = 0; i < NB && i < (int)hist.cnt.size(); ++i) {
        cnt[i][0] = hist.cnt[i][0]; cnt[i][1] = hist.cnt[i][1];
    }

    uint32_t idx = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = layout[oi];
        int w = s.w, h = s.h;
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? layout[pidx].w : 0, ph = (pidx >= 0) ? layout[pidx].h : 0;
        int B = sub_maxbits[oi];
        StaticClusterModel model; model.init(NB, cnt);
        BitplaneRans::Decoder d; d.init(streams[oi]);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < s.coeffs.size(); ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
                if (sig[oi][ci] == 0) {
                    LCFeat f; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 0, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t mlp0 = learned_predict_p0(f);
                    int cluster = r6c_cluster(0, mlp0, kb);
                    uint16_t dp0 = model.predict(f, cluster, mlp0);
                    uint8_t bit = d.decode_symbol(dp0);
                    model.update(f, bit); ++idx;
                    if (bit) {
                        LCFeat fs; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        int csg = r6c_cluster(1, mlp0, kb);
                        uint16_t dp0s = model.predict(fs, csg, mlp0);
                        uint8_t sg = d.decode_symbol(dp0s);
                        model.update(fs, sg); ++idx;
                        sig[oi][ci] = 1; signv[oi][ci] = sg ? -1 : 1;
                        value[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    LCFeat f; learned_features(sig[oi], value[oi], (pidx>=0?&value[pidx]:nullptr), pw, ph, lmag, w, h, x, y, p, 2, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t mlp0 = learned_predict_p0(f);
                    int cluster = r6c_cluster(2, mlp0, kb);
                    uint16_t dp0r = model.predict(f, cluster, mlp0);
                    uint8_t rb = d.decode_symbol(dp0r);
                    model.update(f, rb); ++idx;
                    if (rb) value[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }

    if (total_symbols != 0 && idx != total_symbols)
        throw std::runtime_error("BitplaneCoder::decode_static_cluster: symbol count mismatch");

    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        for (size_t ci = 0; ci < n; ++ci)
            out[oi].coeffs[ci] = (int32_t)value[oi][ci] * signv[oi][ci];
    }
    return out;
}

StaticTreeBitplaneResult BitplaneCoder::encode_static_tree(
    const std::vector<Subband>& subbands, int k, float W, int maxbits_override,
    const std::vector<std::vector<int32_t>>* luma_mag) const {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    size_t NS = subbands.size();
    int K = k;
    int K3 = 3 * K;

    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS), curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0); magv[oi].resize(n); curmag[oi].assign(n, 0);
        sgn[oi].resize(n); topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m; sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }

    // Pass 1: walk and accumulate per-leaf per-symtype counts. The leaf id is
    // derived from RAW already-coded magnitudes (a baked constant at decode).
    StaticTreeHist hist;
    hist.k = K;
    hist.w = W;
    hist.sp0.assign((size_t)K3, (uint16_t)(StaticTreeModel::M / 2));
    std::vector<std::vector<uint32_t>> cnt(K3, std::vector<uint32_t>(2, 0));
    std::vector<std::vector<uint8_t>> bits_by_sub(NS);
    uint32_t total = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        int B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        total += (uint32_t)(n * (size_t)B);
        for (size_t ci = 0; ci < n; ++ci)
            if (magv[oi][ci] > 0) ++total;
    }
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                uint8_t bit; uint8_t symtype;
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    bit = becomes ? 1 : 0; symtype = 0;
                    R6DRaw r; r6d_raw_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr),
                                               pw, ph, lmag, w, h, x, y, p, 0, (int)s.orient, s.level,
                                               parent_sig ? 1 : 0, fc, dg, r);
                    int leaf = r6d_leaf_id(r, K);
                    cnt[(size_t)leaf * 3 + 0][bit]++;
                    bits_by_sub[oi].push_back(bit);
                    if (becomes) {
                        uint8_t sg = sgn[oi][ci]; symtype = 1;
                        R6DRaw rs; r6d_raw_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr),
                                                   pw, ph, lmag, w, h, x, y, p, 1, (int)s.orient, s.level,
                                                   parent_sig ? 1 : 0, fc, dg, rs);
                        int leaf2 = r6d_leaf_id(rs, K);
                        cnt[(size_t)leaf2 * 3 + 1][sg]++;
                        bits_by_sub[oi].push_back(sg);
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    bit = (uint8_t)((magv[oi][ci] >> p) & 1); symtype = 2;
                    R6DRaw r; r6d_raw_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr),
                                              pw, ph, lmag, w, h, x, y, p, 2, (int)s.orient, s.level,
                                              parent_sig ? 1 : 0, fc, dg, r);
                    int leaf = r6d_leaf_id(r, K);
                    cnt[(size_t)leaf * 3 + 2][bit]++;
                    bits_by_sub[oi].push_back(bit);
                    if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
                (void)symtype;
            }
        }
    }

    // Build the transmitted static P(0)*M per leaf/symtype (sign forced neutral).
    for (int leaf = 0; leaf < K; ++leaf) {
        for (int st = 0; st < 3; ++st) {
            uint32_t c0 = cnt[(size_t)leaf * 3 + st][0];
            uint32_t c1 = cnt[(size_t)leaf * 3 + st][1];
            uint32_t tot = c0 + c1;
            uint16_t v;
            if (st == 1) v = (uint16_t)(StaticTreeModel::M / 2);
            else v = (tot == 0) ? (uint16_t)(StaticTreeModel::M / 2)
                                 : (uint16_t)((uint32_t)((uint64_t)c0 * StaticTreeModel::M / tot) & 0xFFFF);
            if (v < 1) v = 1;
            if (v > (uint16_t)StaticTreeModel::M - 1) v = (uint16_t)(StaticTreeModel::M - 1);
            hist.sp0[(size_t)leaf * 3 + st] = v;
        }
    }

    // Pass 2: re-walk (fresh per-subband state), blend transmitted backbone with
    // EMA, rANS-encode. Mirror encode_static_cluster exactly (model reset per
    // subband so the adaptive EMA evolves identically to decode).
    std::vector<std::vector<uint8_t>> streams(NS);
    std::vector<std::vector<uint8_t>> lsig(NS);
    std::vector<std::vector<int32_t>> lcurmag(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        lsig[oi].assign(n, 0);
        lcurmag[oi].assign(n, 0);
    }
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        const auto& bits = bits_by_sub[oi];
        size_t kk = 0;
        std::vector<uint16_t> p0vec;
        p0vec.reserve(bits.size());
        StaticTreeModel model; model.init(K, hist.sp0); model.W_STATIC = W;
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = lsig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(lsig[oi], w, h, x, y, fc, dg);
                const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
                const std::vector<int32_t>* parent_cur = (pidx >= 0) ? &lcurmag[pidx] : nullptr;
                if (lsig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    uint8_t bit = bits[kk++];
                    R6DRaw r; r6d_raw_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 0, (int)s.orient, s.level, parent_sig ? 1 : 0, fc, dg, r);
                    LCFeat f; learned_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 0, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    p0vec.push_back(model.predict(r, f));
                    model.update(f, bit);
                    if (becomes) {
                        uint8_t sg = bits[kk++];
                        R6DRaw rs; r6d_raw_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 1, (int)s.orient, s.level, parent_sig ? 1 : 0, fc, dg, rs);
                        LCFeat fs; learned_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        p0vec.push_back(model.predict(rs, fs));
                        model.update(fs, sg);
                        lsig[oi][ci] = 1; lcurmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    uint8_t bit = bits[kk++];
                    R6DRaw r; r6d_raw_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 2, (int)s.orient, s.level, parent_sig ? 1 : 0, fc, dg, r);
                    LCFeat f; learned_features(lsig[oi], lcurmag[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 2, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    p0vec.push_back(model.predict(r, f));
                    model.update(f, bit);
                    if (bit) lcurmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
        BitplaneRans rans;
        streams[oi] = rans.encode(bits, p0vec);
    }

    StaticTreeBitplaneResult res;
    res.streams = std::move(streams);
    res.sub_maxbits = std::move(sub_maxbits);
    res.total_symbols = total;
    res.hist = std::move(hist);
    return res;
}

std::vector<Subband> BitplaneCoder::decode_static_tree(
    const std::vector<std::vector<uint8_t>>& streams,
    const std::vector<Subband>& layout,
    const std::vector<uint8_t>& sub_maxbits,
    uint32_t total_symbols,
    const StaticTreeHist& hist,
    const std::vector<std::vector<int32_t>>* luma_mag) const {
    int ml = 0;
    auto order = coding_order(layout, ml);
    auto parent = build_parent_map(layout, ml);
    size_t NS = layout.size();
    int K = hist.k;

    std::vector<Subband> out = layout;
    for (auto& s : out) s.coeffs.assign((size_t)s.w * s.h, 0);

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> value(NS);
    std::vector<std::vector<int8_t>> signv(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        sig[oi].assign(n, 0); value[oi].resize(n, 0); signv[oi].assign(n, 1);
    }

    uint32_t idx = 0;
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = layout[oi];
        int w = s.w, h = s.h;
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? layout[pidx].w : 0, ph = (pidx >= 0) ? layout[pidx].h : 0;
        int B = sub_maxbits[oi];
        StaticTreeModel model; model.init(K, hist.sp0); model.W_STATIC = hist.w;
        BitplaneRans::Decoder d; d.init(streams[oi]);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < s.coeffs.size(); ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
                const std::vector<int32_t>* parent_cur = (pidx >= 0) ? &value[pidx] : nullptr;
                if (sig[oi][ci] == 0) {
                    R6DRaw r; r6d_raw_features(sig[oi], value[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 0, (int)s.orient, s.level, parent_sig ? 1 : 0, fc, dg, r);
                    LCFeat f; learned_features(sig[oi], value[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 0, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t dp0 = model.predict(r, f);
                    uint8_t bit = d.decode_symbol(dp0);
                    model.update(f, bit); ++idx;
                    if (bit) {
                        R6DRaw rs; r6d_raw_features(sig[oi], value[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 1, (int)s.orient, s.level, parent_sig ? 1 : 0, fc, dg, rs);
                        LCFeat fs; learned_features(sig[oi], value[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 1, s.level, fs);
                        fs.orient = (uint8_t)s.orient; fs.parent_sig = parent_sig ? 1 : 0; fs.fc = (uint8_t)fc; fs.dg = (uint8_t)dg;
                        uint16_t dp0s = model.predict(rs, fs);
                        uint8_t sg = d.decode_symbol(dp0s);
                        model.update(fs, sg); ++idx;
                        sig[oi][ci] = 1; signv[oi][ci] = sg ? -1 : 1;
                        value[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    R6DRaw r; r6d_raw_features(sig[oi], value[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 2, (int)s.orient, s.level, parent_sig ? 1 : 0, fc, dg, r);
                    LCFeat f; learned_features(sig[oi], value[oi], parent_cur, pw, ph, lmag, w, h, x, y, p, 2, s.level, f);
                    f.orient = (uint8_t)s.orient; f.parent_sig = parent_sig ? 1 : 0; f.fc = (uint8_t)fc; f.dg = (uint8_t)dg;
                    uint16_t dp0r = model.predict(r, f);
                    uint8_t rb = d.decode_symbol(dp0r);
                    model.update(f, rb); ++idx;
                    if (rb) value[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }

    if (total_symbols != 0 && idx != total_symbols)
        throw std::runtime_error("BitplaneCoder::decode_static_tree: symbol count mismatch");

    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = out[oi].coeffs.size();
        for (size_t ci = 0; ci < n; ++ci)
            out[oi].coeffs[ci] = (int32_t)value[oi][ci] * signv[oi][ci];
    }
    return out;
}

void BitplaneCoder::collect_r6d_samples(const std::vector<Subband>& subbands,
                                        std::vector<R6DSample>& out, int maxbits_override,
                                        const std::vector<std::vector<int32_t>>* luma_mag) {
    int ml = 0;
    auto order = coding_order(subbands, ml);
    auto parent = build_parent_map(subbands, ml);
    size_t NS = subbands.size();

    std::vector<uint8_t> sub_maxbits(NS, 0);
    for (size_t oi = 0; oi < NS; ++oi) {
        int B = 1;
        for (int32_t c : subbands[oi].coeffs) {
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            int b = (m == 0) ? 0 : floor_log2(m) + 1;
            if (b > B) B = b;
        }
        if (maxbits_override > 0) B = maxbits_override;
        sub_maxbits[oi] = (uint8_t)B;
    }

    std::vector<std::vector<uint8_t>> sig(NS);
    std::vector<std::vector<int32_t>> magv(NS), curmag(NS);
    std::vector<std::vector<uint8_t>> sgn(NS);
    std::vector<std::vector<int>> topbit(NS);
    for (size_t oi = 0; oi < NS; ++oi) {
        size_t n = subbands[oi].coeffs.size();
        sig[oi].assign(n, 0); magv[oi].resize(n); curmag[oi].assign(n, 0);
        sgn[oi].resize(n); topbit[oi].assign(n, -1);
        for (size_t ci = 0; ci < n; ++ci) {
            int32_t c = subbands[oi].coeffs[ci];
            uint32_t m = (uint32_t)(c < 0 ? -c : c);
            magv[oi][ci] = (int32_t)m; sgn[oi][ci] = (c < 0) ? 1 : 0;
            topbit[oi][ci] = (m == 0) ? -1 : floor_log2(m);
        }
    }
    for (size_t si = 0; si < order.size(); ++si) {
        size_t oi = order[si];
        const Subband& s = subbands[oi];
        int w = s.w, h = s.h, B = sub_maxbits[oi];
        size_t n = subbands[oi].coeffs.size();
        int pidx = parent[oi];
        int pw = (pidx >= 0) ? subbands[pidx].w : 0;
        int ph = (pidx >= 0) ? subbands[pidx].h : 0;
        const std::vector<int32_t>* lmag = (luma_mag ? &(*luma_mag)[oi] : nullptr);
        for (int p = B - 1; p >= 0; --p) {
            for (size_t ci = 0; ci < n; ++ci) {
                int x = (int)(ci % w), y = (int)(ci / w);
                bool parent_sig = false;
                if (pidx >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < pw && pcy < ph)
                        parent_sig = sig[pidx][(size_t)pcy * pw + pcx] != 0;
                }
                int fc = 0, dg = 0;
                neighbor_counts(sig[oi], w, h, x, y, fc, dg);
                if (sig[oi][ci] == 0) {
                    bool becomes = (topbit[oi][ci] == p);
                    uint8_t bit = becomes ? 1 : 0;
                    R6DRaw r; r6d_raw_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr),
                                              pw, ph, lmag, w, h, x, y, p, 0, (int)s.orient, s.level,
                                              parent_sig ? 1 : 0, fc, dg, r);
                    out.push_back({r, bit});
                    if (becomes) {
                        uint8_t sg = sgn[oi][ci];
                        R6DRaw rs; r6d_raw_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr),
                                                   pw, ph, lmag, w, h, x, y, p, 1, (int)s.orient, s.level,
                                                   parent_sig ? 1 : 0, fc, dg, rs);
                        out.push_back({rs, sg});
                        sig[oi][ci] = 1; curmag[oi][ci] = (int32_t)(1 << p);
                    }
                } else {
                    uint8_t bit = (uint8_t)((magv[oi][ci] >> p) & 1);
                    R6DRaw r; r6d_raw_features(sig[oi], curmag[oi], (pidx>=0?&curmag[pidx]:nullptr),
                                              pw, ph, lmag, w, h, x, y, p, 2, (int)s.orient, s.level,
                                              parent_sig ? 1 : 0, fc, dg, r);
                    out.push_back({r, bit});
                    if (bit) curmag[oi][ci] |= (int32_t)(1 << p);
                }
            }
        }
    }
}

int r6d_leaf_count() { return R6D_K; }

} // namespace prism::codec
