// Option C: Learned Pyramid Codec (L3C-style, issue #130).
//
// Multi-scale learned analysis/synthesis transform using reversible integer
// lifting with learned MLP predict steps. Byte-exact reversible (invariant I26).

#include "prism/codec/option_c.h"
#include "prism/codec/color.h"
#include "option_c_data.inc" // baked int16 weights (generated by train_option_c.py)
#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace prism::codec {

// -----------------------------------------------------------------------
// Integer MLP predict (identical structure to Route 10, different weights).
// -----------------------------------------------------------------------

namespace {
inline int64_t fdivQ(int64_t x) {
    int64_t r = x / OptionCPredict::Q;
    if ((x % OptionCPredict::Q) != 0 && x < 0) --r;
    return r;
}
} // namespace

int32_t OptionCPredict::predict(int32_t lv, int32_t rv) const {
    int64_t acc = b2;
    for (int j = 0; j < H; ++j) {
        int64_t z = (int64_t)b1[j] + (int64_t)W1[j][0] * lv + (int64_t)W1[j][1] * rv;
        int64_t a = fdivQ(z);
        if (a > 0) acc += (int64_t)W2[j] * a;
    }
    return (int32_t)fdivQ(acc);
}

// -----------------------------------------------------------------------
// 1D reversible lifting (predict + update).
// -----------------------------------------------------------------------

void option_c_forward_1d(const int32_t* even, size_t en,
                         const int32_t* odd, size_t on,
                         int32_t* out_even, int32_t* out_odd,
                         const OptionCPredict& pred, const OptionCUpdate& upd) {
    // Predict: residual = odd[k] - (base + mlp(even[k], even[k+1]))
    for (size_t k = 0; k < on; ++k) {
        int32_t lv = even[k];
        int32_t rv = (k + 1 < en) ? even[k + 1] : even[k];
        int32_t base = (lv + rv) >> 1;
        out_odd[k] = odd[k] - (base + pred.predict(lv, rv));
    }
    // Update: out_even[k] = even[k] + update(out_odd[k-1], out_odd[k])
    // Uses the LeGall 5/3 linear update (the learnability is in predict).
    for (size_t k = 0; k < en; ++k) {
        int32_t lo = (k > 0 && on > 0) ? out_odd[k - 1] : (on > 0 ? out_odd[0] : 0);
        int32_t ro = (k < on) ? out_odd[k] : (on > 0 ? out_odd[on - 1] : 0);
        int32_t update_val = ((int64_t)lo + (int64_t)ro) * upd.scale_num / upd.scale_den / 2;
        out_even[k] = even[k] + (int32_t)update_val;
    }
}

void option_c_inverse_1d(const int32_t* out_even, size_t en,
                         const int32_t* out_odd, size_t on,
                         int32_t* even, int32_t* odd,
                         const OptionCPredict& pred, const OptionCUpdate& upd) {
    // Undo update: even[k] = out_even[k] - update(out_odd[k-1], out_odd[k])
    std::vector<int32_t> e(en);
    for (size_t k = 0; k < en; ++k) {
        int32_t lo = (k > 0 && on > 0) ? out_odd[k - 1] : (on > 0 ? out_odd[0] : 0);
        int32_t ro = (k < on) ? out_odd[k] : (on > 0 ? out_odd[on - 1] : 0);
        int32_t update_val = ((int64_t)lo + (int64_t)ro) * upd.scale_num / upd.scale_den / 2;
        e[k] = out_even[k] - (int32_t)update_val;
    }
    // Undo predict: odd[k] = out_odd[k] + (base + mlp(even[k], even[k+1]))
    for (size_t k = 0; k < on; ++k) {
        int32_t lv = e[k];
        int32_t rv = (k + 1 < en) ? e[k + 1] : e[k];
        int32_t base = (lv + rv) >> 1;
        odd[k] = out_odd[k] + (base + pred.predict(lv, rv));
    }
    for (size_t k = 0; k < en; ++k) even[k] = e[k];
}

// -----------------------------------------------------------------------
// 2D separable analysis/synthesis (rows then columns, per scale).
// -----------------------------------------------------------------------

namespace {
// Helper: apply 1D lifting to rows of a w*h buffer.
void lift_rows(std::vector<int32_t>& buf, uint32_t w, uint32_t h,
               const OptionCPredict& pred, const OptionCUpdate& upd) {
    for (uint32_t y = 0; y < h; ++y) {
        int32_t* row = buf.data() + y * w;
        size_t en = (w + 1) / 2;  // number of even samples
        size_t on = w / 2;         // number of odd samples
        std::vector<int32_t> ev(en), od(on);
        // Split into even/odd
        for (size_t k = 0; k < en; ++k) ev[k] = row[2 * k];
        for (size_t k = 0; k < on; ++k) od[k] = row[2 * k + 1];
        // Forward lifting
        std::vector<int32_t> oe(en), oo(on);
        option_c_forward_1d(ev.data(), en, od.data(), on,
                            oe.data(), oo.data(), pred, upd);
        // Interleave back: [oe[0], oo[0], oe[1], oo[1], ...]
        for (size_t k = 0; k < en; ++k) row[2 * k] = oe[k];
        for (size_t k = 0; k < on; ++k) row[2 * k + 1] = oo[k];
    }
}

void unlift_rows(std::vector<int32_t>& buf, uint32_t w, uint32_t h,
                 const OptionCPredict& pred, const OptionCUpdate& upd) {
    for (uint32_t y = 0; y < h; ++y) {
        int32_t* row = buf.data() + y * w;
        size_t en = (w + 1) / 2;
        size_t on = w / 2;
        std::vector<int32_t> oe(en), oo(on);
        for (size_t k = 0; k < en; ++k) oe[k] = row[2 * k];
        for (size_t k = 0; k < on; ++k) oo[k] = row[2 * k + 1];
        std::vector<int32_t> ev(en), od(on);
        option_c_inverse_1d(oe.data(), en, oo.data(), on,
                            ev.data(), od.data(), pred, upd);
        for (size_t k = 0; k < en; ++k) row[2 * k] = ev[k];
        for (size_t k = 0; k < on; ++k) row[2 * k + 1] = od[k];
    }
}

// Helper: apply 1D lifting to columns of a w*h buffer.
void lift_cols(std::vector<int32_t>& buf, uint32_t w, uint32_t h,
               const OptionCPredict& pred, const OptionCUpdate& upd) {
    for (uint32_t x = 0; x < w; ++x) {
        size_t en = (h + 1) / 2;
        size_t on = h / 2;
        std::vector<int32_t> ev(en), od(on);
        for (size_t k = 0; k < en; ++k) ev[k] = buf[(2 * k) * w + x];
        for (size_t k = 0; k < on; ++k) od[k] = buf[(2 * k + 1) * w + x];
        std::vector<int32_t> oe(en), oo(on);
        option_c_forward_1d(ev.data(), en, od.data(), on,
                            oe.data(), oo.data(), pred, upd);
        for (size_t k = 0; k < en; ++k) buf[(2 * k) * w + x] = oe[k];
        for (size_t k = 0; k < on; ++k) buf[(2 * k + 1) * w + x] = oo[k];
    }
}

void unlift_cols(std::vector<int32_t>& buf, uint32_t w, uint32_t h,
                 const OptionCPredict& pred, const OptionCUpdate& upd) {
    for (uint32_t x = 0; x < w; ++x) {
        size_t en = (h + 1) / 2;
        size_t on = h / 2;
        std::vector<int32_t> oe(en), oo(on);
        for (size_t k = 0; k < en; ++k) oe[k] = buf[(2 * k) * w + x];
        for (size_t k = 0; k < on; ++k) oo[k] = buf[(2 * k + 1) * w + x];
        std::vector<int32_t> ev(en), od(on);
        option_c_inverse_1d(oe.data(), en, oo.data(), on,
                            ev.data(), od.data(), pred, upd);
        for (size_t k = 0; k < en; ++k) buf[(2 * k) * w + x] = ev[k];
        for (size_t k = 0; k < on; ++k) buf[(2 * k + 1) * w + x] = od[k];
    }
}
} // namespace

// -----------------------------------------------------------------------
// Full 2D analysis (3-scale).
// -----------------------------------------------------------------------

std::vector<OptionCSubband> option_c_analysis(const std::vector<int32_t>& plane,
                                               uint32_t w, uint32_t h,
                                               const OptionCParams& params) {
    std::vector<OptionCSubband> result;
    if (w == 0 || h == 0) return result;

    std::vector<int32_t> buf = plane;
    uint32_t cw = w, ch = h;

    for (int scale = 0; scale < OptionCParams::NUM_SCALES; ++scale) {
        const auto& pred_r = params.row_predict[scale];
        const auto& upd_r = params.row_update[scale];
        const auto& pred_c = params.col_predict[scale];
        const auto& upd_c = params.col_update[scale];

        // Forward lifting: rows then columns
        lift_rows(buf, cw, ch, pred_r, upd_r);
        lift_cols(buf, cw, ch, pred_c, upd_c);

        // Split into LL (top-left quadrant) and detail bands
        uint32_t hw = (cw + 1) / 2;
        uint32_t hh = (ch + 1) / 2;
        uint32_t dw = cw / 2;
        uint32_t dh = ch / 2;

        // Extract HL (top-right), LH (bottom-left), HH (bottom-right)
        auto extract_band = [&](uint32_t x0, uint32_t y0, uint32_t bw, uint32_t bh,
                                OptionCSubband::Orient orient) {
            OptionCSubband sb;
            sb.orient = orient;
            sb.scale = scale + 1; // scale 1..NUM_SCALES
            sb.w = bw;
            sb.h = bh;
            sb.coeffs.resize(bw * bh);
            for (uint32_t y = 0; y < bh; ++y)
                for (uint32_t x = 0; x < bw; ++x)
                    sb.coeffs[y * bw + x] = buf[(y0 + y) * cw + (x0 + x)];
            return sb;
        };

        if (dw > 0 && dh > 0) {
            result.push_back(extract_band(hw, 0, dw, hh, OptionCSubband::Orient::HL));
            result.push_back(extract_band(0, hh, hw, dh, OptionCSubband::Orient::LH));
            result.push_back(extract_band(hw, hh, dw, dh, OptionCSubband::Orient::HH));
        }

        // Update buf to LL quadrant for next scale
        std::vector<int32_t> ll(hw * hh);
        for (uint32_t y = 0; y < hh; ++y)
            for (uint32_t x = 0; x < hw; ++x)
                ll[y * hw + x] = buf[y * cw + x];
        buf = std::move(ll);
        cw = hw;
        ch = hh;
    }

    // Add the final LL subband (coarsest scale)
    OptionCSubband ll_sb;
    ll_sb.orient = OptionCSubband::Orient::LL;
    ll_sb.scale = 0;
    ll_sb.w = cw;
    ll_sb.h = ch;
    ll_sb.coeffs = std::move(buf);
    result.push_back(std::move(ll_sb));

    return result;
}

// -----------------------------------------------------------------------
// Full 2D synthesis (3-scale, inverse order).
// -----------------------------------------------------------------------

std::vector<int32_t> option_c_synthesis(const std::vector<OptionCSubband>& subbands,
                                         uint32_t w, uint32_t h,
                                         const OptionCParams& params) {
    // Find the LL subband (coarsest scale)
    const OptionCSubband* ll_ptr = nullptr;
    for (auto& sb : subbands) {
        if (sb.scale == 0 && sb.orient == OptionCSubband::Orient::LL) {
            ll_ptr = &sb;
            break;
        }
    }
    if (!ll_ptr) throw std::runtime_error("OptionC: missing LL subband");

    // Start from the LL subband and upscale through each scale
    std::vector<int32_t> buf = ll_ptr->coeffs;
    uint32_t cw = ll_ptr->w;
    uint32_t ch = ll_ptr->h;

    // Process scales in reverse order (coarsest to finest)
    for (int scale = OptionCParams::NUM_SCALES; scale >= 1; --scale) {
        // Find the three detail bands for this scale
        const OptionCSubband *hl = nullptr, *lh = nullptr, *hh = nullptr;
        for (auto& sb : subbands) {
            if (sb.scale == scale) {
                switch (sb.orient) {
                    case OptionCSubband::Orient::HL: hl = &sb; break;
                    case OptionCSubband::Orient::LH: lh = &sb; break;
                    case OptionCSubband::Orient::HH: hh = &sb; break;
                    default: break;
                }
            }
        }
        if (!hl || !lh || !hh) throw std::runtime_error("OptionC: missing detail bands");

        // Reconstruct full-resolution buffer: LL in top-left, details in other quadrants
        uint32_t llw = cw;  // LL width
        uint32_t llh = ch;  // LL height
        uint32_t dw = hl->w; // detail width
        uint32_t dh = lh->h; // detail height
        uint32_t fw = llw + dw; // full width
        uint32_t fh = llh + dh; // full height

        std::vector<int32_t> full(fw * fh, 0);
        // Copy LL to top-left
        for (uint32_t y = 0; y < llh; ++y)
            for (uint32_t x = 0; x < llw; ++x)
                full[y * fw + x] = buf[y * llw + x];
        // Copy HL to top-right
        for (uint32_t y = 0; y < llh; ++y)
            for (uint32_t x = 0; x < dw; ++x)
                full[y * fw + (llw + x)] = hl->coeffs[y * dw + x];
        // Copy LH to bottom-left
        for (uint32_t y = 0; y < dh; ++y)
            for (uint32_t x = 0; x < llw; ++x)
                full[(llh + y) * fw + x] = lh->coeffs[y * llw + x];
        // Copy HH to bottom-right
        for (uint32_t y = 0; y < dh; ++y)
            for (uint32_t x = 0; x < dw; ++x)
                full[(llh + y) * fw + (llw + x)] = hh->coeffs[y * dw + x];

        const auto& pred_c = params.col_predict[scale - 1];
        const auto& upd_c = params.col_update[scale - 1];
        const auto& pred_r = params.row_predict[scale - 1];
        const auto& upd_r = params.row_update[scale - 1];

        // Inverse lifting: columns then rows (reverse of analysis)
        unlift_cols(full, fw, fh, pred_c, upd_c);
        unlift_rows(full, fw, fh, pred_r, upd_r);

        buf = std::move(full);
        cw = fw;
        ch = fh;
    }

    return buf;
}

// -----------------------------------------------------------------------
// Frame-level encode/decode (stub for now, full implementation in M4).
// -----------------------------------------------------------------------

std::vector<uint8_t> frame_option_c_encode(const Raster& raster, size_t& net_out) {
    // TODO: Full implementation in M4 (wire format, histograms, static ANS).
    // For now, just run the analysis transform and return the subbands.
    const auto& params = baked_option_c_params();
    std::vector<uint8_t> result;

    for (size_t c = 0; c < raster.num_channels(); ++c) {
        // Convert u16 plane to int32
        const auto& plane = raster.planes[c];
        std::vector<int32_t> i32(plane.begin(), plane.end());

        // Run analysis transform
        auto subbands = option_c_analysis(i32, raster.w, raster.h, params);

        // TODO: entropy code subbands with transmitted histograms
        // For now, just verify the roundtrip
        auto reconstructed = option_c_synthesis(subbands, raster.w, raster.h, params);

        // Byte-exact check
        for (size_t i = 0; i < plane.size(); ++i) {
            if (reconstructed[i] != (int32_t)plane[i]) {
                throw std::runtime_error("OptionC: roundtrip mismatch");
            }
        }
    }

    net_out = result.size();
    return result;
}

Raster frame_option_c_decode(const std::vector<uint8_t>& bytes) {
    // TODO: Full implementation in M4.
    throw std::runtime_error("OptionC decode: not yet implemented");
}

} // namespace prism::codec
