// Learned wavelet-domain coefficient predictor (Route 4 / X6a, lever L1).
//
// A baked LINEAR model per subband orientation (LL, HL, LH, HH) regresses a
// coefficient from a causal window of already-reconstructed neighbours (same
// subband 3x3 up/left/diagonals + parent + same-level sibling orientations). The
// residual r = c - c_hat is coded by the existing byte-exact bitplane coder; the
// predictor removes magnitude bits that the per-context model cannot (X2 entropy
// diagnostic: the bitplane coder is entropy-near-optimal, so the remaining gap
// is SOURCE entropy). No predictor state is transmitted: weights are baked
// constants (invariant I29), the round trip stays byte-exact, and encode/decode
// compute identical c_hat because only strictly-earlier coefficients are read.
//
// The weights are generated by `prism train-predictor` (ridge regression on real
// Kodak coefficients) and shipped in predictor_data.inc. An all-zero model
// (default before training) predicts c_hat = 0, i.e. the residual path is then
// identical to the non-residual path.

#include "prism/codec/predictor.h"
#include <cmath>
#include <algorithm>

namespace prism::codec {

namespace {

#include "predictor_data.inc"

PredictWeights baked_weights() {
    PredictWeights w;
    for (int o = 0; o < 4; ++o) {
        w.bias[o] = PRED_BIAS[o];
        for (int k = 0; k < 8; ++k) w.w[o][k] = PRED_W[o][k];
    }
    return w;
}

} // namespace

CoefficientPredictor::CoefficientPredictor() : weights_(baked_weights()) {}

void CoefficientPredictor::build_topology(const std::vector<Subband>& subs,
                                           std::vector<int>& order,
                                           std::vector<int>& parent,
                                           std::vector<int>& sib1,
                                           std::vector<int>& sib2) {
    int ml = 0;
    for (const auto& s : subs) if (s.level > ml) ml = s.level;
    std::vector<int> map(4 * (ml + 1), -1);
    for (int i = 0; i < (int)subs.size(); ++i)
        map[(int)subs[i].orient * (ml + 1) + subs[i].level] = i;
    order.clear();
    if (map[0 * (ml + 1) + 0] >= 0) order.push_back(map[0 * (ml + 1) + 0]);
    for (int L = 1; L <= ml; ++L)
        for (int o = 1; o <= 3; ++o) {
            int idx = map[o * (ml + 1) + L];
            if (idx >= 0) order.push_back(idx);
        }
    parent.assign(subs.size(), -1);
    sib1.assign(subs.size(), -1);
    sib2.assign(subs.size(), -1);
    for (int i = 0; i < (int)subs.size(); ++i) {
        const Subband& s = subs[i];
        if (s.level == 0) { parent[i] = -1; }
        else if (s.level == 1) parent[i] = map[0 * (ml + 1) + 0];
        else parent[i] = map[(int)s.orient * (ml + 1) + (s.level - 1)];
        // Earlier same-level sibling orientations (causal: only those emitted
        // before this subband in coding order are available).
        if (s.orient == Subband::Orient::LH) {
            int hl = map[1 * (ml + 1) + s.level];
            if (hl >= 0 && hl != i) sib1[i] = hl;
        } else if (s.orient == Subband::Orient::HH) {
            int hl = map[1 * (ml + 1) + s.level];
            int lh = map[2 * (ml + 1) + s.level];
            if (hl >= 0 && hl != i) sib1[i] = hl;
            if (lh >= 0 && lh != i) sib2[i] = lh;
        }
    }
}

// Read reconstructed coefficient (x,y) of subband si; out-of-bounds or
// not-yet-available positions return 0 (causal, symmetric at encode/decode).
static inline int32_t rc(const std::vector<std::vector<int32_t>>& recon,
                         const std::vector<Subband>& subs, int si, int x, int y) {
    const Subband& s = subs[si];
    if (x < 0 || y < 0 || x >= s.w || y >= s.h) return 0;
    return recon[si][(size_t)y * s.w + x];
}

int32_t CoefficientPredictor::predict(const std::vector<std::vector<int32_t>>& recon,
                                      const std::vector<Subband>& subs,
                                      const std::vector<int>& parent,
                                      const std::vector<int>& sib1,
                                      const std::vector<int>& sib2,
                                      int si, int x, int y) const {
    const Subband& s = subs[si];
    int32_t f[8] = {0, 0, 0, 0, 0, 0, 0, 0};
    int32_t L = (x - 1 >= 0) ? rc(recon, subs, si, x - 1, y) : 0;          // left
    int32_t U = (y - 1 >= 0) ? rc(recon, subs, si, x, y - 1) : 0;          // up
    int32_t UL = (x - 1 >= 0 && y - 1 >= 0) ? rc(recon, subs, si, x - 1, y - 1) : 0; // up-left
    // JPEG-LS-style median edge predictor (dominant nonlinear term).
    int32_t a = L, b = U, c = UL;
    int32_t lo = std::min({a, b, c}), hi = std::max({a, b, c});
    int32_t medv = (a + b + c) - lo - hi;
    f[0] = medv;
    f[1] = L;
    f[2] = U;
    f[3] = UL;
    f[4] = (x + 1 < s.w && y - 1 >= 0) ? rc(recon, subs, si, x + 1, y - 1) : 0; // up-right
    int p = parent[si];
    if (p >= 0) {
        int pcx = x >> 1, pcy = y >> 1;
        if (pcx < subs[p].w && pcy < subs[p].h)
            f[5] = recon[p][(size_t)pcy * subs[p].w + pcx];
    }
    int s1 = sib1[si];
    if (s1 >= 0) f[6] = rc(recon, subs, s1, x, y);
    int s2 = sib2[si];
    if (s2 >= 0) f[7] = rc(recon, subs, s2, x, y);

    const PredictWeights& w = weights_;
    int o = (int)s.orient;
    float acc = w.bias[o];
    for (int k = 0; k < 8; ++k) acc += w.w[o][k] * (float)f[k];
    return (int32_t)std::lround((double)acc);
}

void CoefficientPredictor::collect_samples(const std::vector<Subband>& subs,
                                            std::vector<PredictSample>& out) {
    std::vector<int> order, parent, sib1, sib2;
    build_topology(subs, order, parent, sib1, sib2);
    // `get` reads the TRUE coefficient (recon == subs here), which equals the
    // reconstructed value of earlier coefficients - exactly what predict() will
    // see at encode and decode (only strictly-earlier neighbours are ever read).
    auto get = [&](int sidx, int nx, int ny) -> int32_t {
        if (sidx < 0) return 0;
        const Subband& ss = subs[sidx];
        if (nx < 0 || ny < 0 || nx >= ss.w || ny >= ss.h) return 0;
        return subs[sidx].coeffs[(size_t)ny * ss.w + nx];
    };
    for (int si : order) {
        const Subband& s = subs[si];
        for (int y = 0; y < s.h; ++y) {
            for (int x = 0; x < s.w; ++x) {
                PredictSample sm;
                sm.orient = (uint8_t)s.orient;
                sm.target = s.coeffs[(size_t)y * s.w + x];
                int32_t L = (x - 1 >= 0) ? get(si, x - 1, y) : 0;
                int32_t U = (y - 1 >= 0) ? get(si, x, y - 1) : 0;
                int32_t UL = (x - 1 >= 0 && y - 1 >= 0) ? get(si, x - 1, y - 1) : 0;
                int32_t a = L, b = U, c = UL;
                int32_t lo = std::min({a, b, c}), hi = std::max({a, b, c});
                int32_t medv = (a + b + c) - lo - hi;
                sm.feat[0] = medv;
                sm.feat[1] = L;
                sm.feat[2] = U;
                sm.feat[3] = UL;
                sm.feat[4] = (x + 1 < s.w && y - 1 >= 0) ? get(si, x + 1, y - 1) : 0;
                if (parent[si] >= 0) {
                    int pcx = x >> 1, pcy = y >> 1;
                    if (pcx < subs[parent[si]].w && pcy < subs[parent[si]].h)
                        sm.feat[5] = subs[parent[si]].coeffs[(size_t)pcy * subs[parent[si]].w + pcx];
                }
                if (sib1[si] >= 0) sm.feat[6] = get(sib1[si], x, y);
                if (sib2[si] >= 0) sm.feat[7] = get(sib2[si], x, y);
                out.push_back(sm);
            }
        }
    }
}

} // namespace prism::codec
