// Learned wavelet-domain coefficient predictor (Route 4 / X6, lever L2).
//
// A baked per-orientation MLP regresses a coefficient from a causal window of
// already-reconstructed neighbours (same-subband 3x3 up/left/diagonals + parent +
// same-level sibling orientations + derived magnitude/gradient features). The
// residual r = c - c_hat is coded by the existing byte-exact bitplane coder; the
// predictor removes magnitude bits that the per-context model cannot (X2 entropy
// diagnostic: the bitplane coder is entropy-near-optimal, so the remaining gap is
// SOURCE entropy). No predictor state is transmitted: weights are baked constants
// (invariant I29), the round trip stays byte-exact, and encode/decode compute
// identical c_hat because only strictly-earlier coefficients are read.
//
// The weights are generated by `prism train-predictor` (per-orientation MLP, L1 /
// codelength loss on real Kodak coefficients) and shipped in predictor_data.inc.
// An all-zero model (default before training) predicts c_hat = 0, i.e. the
// residual path is then identical to the non-residual path.

#include "prism/codec/predictor.h"
#include <cmath>
#include <algorithm>
#include <cstring>

namespace prism::codec {

namespace {

#include "predictor_data.inc"

PredMLP baked_weights() {
    PredMLP m;
    // PRED_W1 / PRED_B1 / PRED_W2 / PRED_B2 are emitted by train-predictor with
    // the same (4, PRED_NH, PRED_NF) shape; copy them into the runtime struct.
    for (int o = 0; o < 4; ++o) {
        for (int j = 0; j < PRED_NH; ++j) {
            m.b1[o][j] = PRED_B1[o][j];
            m.w2[o][j] = PRED_W2[o][j];
            for (int i = 0; i < PRED_NF; ++i) m.w1[o][j][i] = PRED_W1[o][j][i];
        }
        m.b2[o] = PRED_B2[o];
    }
    return m;
}

} // namespace

CoefficientPredictor::CoefficientPredictor() : mlp_(baked_weights()) {}

void CoefficientPredictor::build_topology(const std::vector<Subband>& subs,
                                          std::vector<int>& order,
                                          std::vector<int>& parent,
                                          std::vector<int>& sib1,
                                          std::vector<int>& sib2) {
    int ml = 0;
    for (const auto& s : subs) if (s.level > ml) ml = s.level;
    std::vector<int> map(4 * (ml + 1), -1);
    for (int i = 0; i < (int)subs.size(); ++i)
        map[(int)subs[i].orient * (ml + 1) + subs[i].level] = i;
    order.clear();
    if (map[0 * (ml + 1) + 0] >= 0) order.push_back(map[0 * (ml + 1) + 0]);
    for (int L = 1; L <= ml; ++L)
        for (int o = 1; o <= 3; ++o) {
            int idx = map[o * (ml + 1) + L];
            if (idx >= 0) order.push_back(idx);
        }
    parent.assign(subs.size(), -1);
    sib1.assign(subs.size(), -1);
    sib2.assign(subs.size(), -1);
    for (int i = 0; i < (int)subs.size(); ++i) {
        const Subband& s = subs[i];
        if (s.level == 0) { parent[i] = -1; }
        else if (s.level == 1) parent[i] = map[0 * (ml + 1) + 0];
        else parent[i] = map[(int)s.orient * (ml + 1) + (s.level - 1)];
        if (s.orient == Subband::Orient::LH) {
            int hl = map[1 * (ml + 1) + s.level];
            if (hl >= 0 && hl != i) sib1[i] = hl;
        } else if (s.orient == Subband::Orient::HH) {
            int hl = map[1 * (ml + 1) + s.level];
            int lh = map[2 * (ml + 1) + s.level];
            if (hl >= 0 && hl != i) sib1[i] = hl;
            if (lh >= 0 && lh != i) sib2[i] = lh;
        }
    }
}

// Read reconstructed coefficient (x,y) of subband si; out-of-bounds or
// not-yet-available positions return 0 (causal, symmetric at encode/decode).
static inline int32_t rc(const std::vector<std::vector<int32_t>>& recon,
                          const std::vector<Subband>& subs, int si, int x, int y) {
    const Subband& s = subs[si];
    if (x < 0 || y < 0 || x >= s.w || y >= s.h) return 0;
    return recon[si][(size_t)y * s.w + x];
}

// Fill the normalised PRED_NF feature vector for coefficient (x,y) of subband si.
// Used identically by predict() and collect_samples() so the trained model is
// symmetric between encode and decode.
static void pred_features(const std::vector<std::vector<int32_t>>& recon,
                          const std::vector<Subband>& subs,
                          const std::vector<int>& parent,
                          const std::vector<int>& sib1,
                          const std::vector<int>& sib2,
                          int si, int x, int y, float feat[PRED_NF]) {
    const Subband& s = subs[si];
    int32_t L = (x - 1 >= 0) ? rc(recon, subs, si, x - 1, y) : 0;          // left
    int32_t U = (y - 1 >= 0) ? rc(recon, subs, si, x, y - 1) : 0;          // up
    int32_t UL = (x - 1 >= 0 && y - 1 >= 0) ? rc(recon, subs, si, x - 1, y - 1) : 0; // up-left
    int32_t a = L, b = U, c = UL;
    int32_t lo = std::min({a, b, c}), hi = std::max({a, b, c});
    int32_t medv = (a + b + c) - lo - hi;                                  // JPEG-LS median edge term
    int32_t UR = (x + 1 < s.w && y - 1 >= 0) ? rc(recon, subs, si, x + 1, y - 1) : 0; // up-right
    int32_t P = 0, S1 = 0, S2 = 0;
    int p = parent[si];
    if (p >= 0) {
        int pcx = x >> 1, pcy = y >> 1;
        if (pcx < subs[p].w && pcy < subs[p].h)
            P = recon[p][(size_t)pcy * subs[p].w + pcx];
    }
    if (sib1[si] >= 0) S1 = rc(recon, subs, sib1[si], x, y);
    if (sib2[si] >= 0) S2 = rc(recon, subs, sib2[si], x, y);

    const float S = 64.0f;
    feat[0] = (float)medv / S;
    feat[1] = (float)L / S;
    feat[2] = (float)U / S;
    feat[3] = (float)UL / S;
    feat[4] = (float)UR / S;
    feat[5] = (float)P / S;
    feat[6] = (float)S1 / S;
    feat[7] = (float)S2 / S;
    feat[8]  = (float)std::abs(L)  / S;
    feat[9]  = (float)std::abs(U)  / S;
    feat[10] = (float)std::abs(UL) / S;
    feat[11] = (float)(U - L) / S;
    feat[12] = (float)std::abs(P)  / S;
    feat[13] = (float)std::abs(S1) / S;
    feat[14] = (float)std::abs(S2) / S;
    feat[15] = (float)s.level / 6.0f;
}

int32_t CoefficientPredictor::predict(const std::vector<std::vector<int32_t>>& recon,
                                       const std::vector<Subband>& subs,
                                       const std::vector<int>& parent,
                                       const std::vector<int>& sib1,
                                       const std::vector<int>& sib2,
                                       int si, int x, int y) const {
    float feat[PRED_NF];
    pred_features(recon, subs, parent, sib1, sib2, si, x, y, feat);
    const PredMLP& m = mlp_;
    int o = (int)subs[si].orient;
    float h[PRED_NH];
    for (int j = 0; j < PRED_NH; ++j) {
        float acc = m.b1[o][j];
        for (int i = 0; i < PRED_NF; ++i) acc += m.w1[o][j][i] * feat[i];
        h[j] = acc > 0.0f ? acc : 0.0f; // ReLU
    }
    float acc = m.b2[o];
    for (int j = 0; j < PRED_NH; ++j) acc += m.w2[o][j] * h[j];
    return (int32_t)std::lround((double)acc);
}

void CoefficientPredictor::collect_samples(const std::vector<Subband>& subs,
                                            std::vector<PredictSample>& out) {
    std::vector<int> order, parent, sib1, sib2;
    build_topology(subs, order, parent, sib1, sib2);
    auto get = [&](int sidx, int nx, int ny) -> int32_t {
        if (sidx < 0) return 0;
        const Subband& ss = subs[sidx];
        if (nx < 0 || ny < 0 || nx >= ss.w || ny >= ss.h) return 0;
        return subs[sidx].coeffs[(size_t)ny * ss.w + nx];
    };
    // At collection time `subs` holds the true coefficients; build a recon view
    // of them once (symmetric with encode, where recon == true c for already-coded
    // positions) and reuse it for every sample.
    std::vector<std::vector<int32_t>> recon(subs.size());
    for (size_t k = 0; k < subs.size(); ++k) recon[k] = subs[k].coeffs;
    for (int si : order) {
        const Subband& s = subs[si];
        for (int y = 0; y < s.h; ++y) {
            for (int x = 0; x < s.w; ++x) {
                PredictSample sm;
                sm.orient = (uint8_t)s.orient;
                sm.target = s.coeffs[(size_t)y * s.w + x];
                pred_features(recon, subs, parent, sib1, sib2, si, x, y, sm.feat);
                (void)get;
                out.push_back(sm);
            }
        }
    }
}

} // namespace prism::codec
