// Route 10 learned nonlinear MLP lifting (issue #130).
//
// Exact integer replica of the numpy fixed-point MLP trained by
// prism/scripts/train_route10.py. See route10_mlp.h for the transform contract.
// The lift is byte-exact reversible (invariant I26): the same baked mlp is run
// on encode and decode, so decode re-adds the identical integer correction.

#include "prism/codec/route10_mlp.h"
#include "route10_mlp_data.inc" // baked int16 weights (generated by train_route10.py)
#include <algorithm>

namespace prism::codec {

namespace {
// Floor division by Q matching arithmetic right shift (C++20 defines signed >>
// as arithmetic; for portability we floor explicitly so negative operands
// match the numpy integer-sim `//` used during training).
inline int64_t fdivQ(int64_t x) {
    int64_t r = x / Route10MLP::Q;
    if ((x % Route10MLP::Q) != 0 && x < 0) --r;
    return r;
}
} // namespace

int32_t Route10MLP::predict(int32_t lv, int32_t rv) const {
    int64_t acc = b2; // b2 is already scaled by Q
    for (int j = 0; j < H; ++j) {
        int64_t z = (int64_t)b1[j] + (int64_t)W1[j][0] * lv + (int64_t)W1[j][1] * rv;
        int64_t a = fdivQ(z); // hidden activation, real units (un-scaled)
        if (a > 0) acc += (int64_t)W2[j] * a; // W2 scaled by Q -> acc stays scaled
    }
    return (int32_t)fdivQ(acc); // real output
}

void forward_learned_mlp(const std::vector<int32_t>& even, const std::vector<int32_t>& odd,
                         std::vector<int32_t>& out_even, std::vector<int32_t>& out_odd) {
    Route10MLP m = baked_route10_mlp();
    size_t en = even.size(), on = odd.size();
    out_even.resize(en);
    out_odd.resize(on);
    // Predict on odd (Learned MLP replaces the linear base).
    for (size_t k = 0; k < on; ++k) {
        int32_t lv = even[k];
        int32_t rv = (k + 1 < en) ? even[k + 1] : even[k];
        int32_t base = (lv + rv) >> 1; // div2 (arithmetic shift == floor(/2))
        out_odd[k] = odd[k] - (base + m.predict(lv, rv));
    }
    // Update on even (linear Le Gall, identical to forward_53).
    for (size_t k = 0; k < en; ++k) {
        int32_t lo = (k > 0) ? (on ? out_odd[k - 1] : 0) : (on ? out_odd[0] : 0);
        int32_t ro = (k < on) ? out_odd[k] : (on ? out_odd[on - 1] : 0);
        out_even[k] = even[k] + ((lo + ro) >> 1);
    }
}

void inverse_learned_mlp(const std::vector<int32_t>& even, const std::vector<int32_t>& odd,
                         std::vector<int32_t>& out) {
    Route10MLP m = baked_route10_mlp();
    size_t en = even.size(), on = odd.size();
    out.resize(en + on);
    std::vector<int32_t> e = even;
    // Undo update on even (linear Le Gall, identical to inverse_53).
    for (size_t k = 0; k < en; ++k) {
        int32_t lo = (k > 0) ? (on ? odd[k - 1] : 0) : (on ? odd[0] : 0);
        int32_t ro = (k < on) ? odd[k] : (on ? odd[on - 1] : 0);
        e[k] = even[k] - ((lo + ro) >> 1);
    }
    // Undo predict on odd (uses recovered e).
    for (size_t k = 0; k < on; ++k) {
        int32_t lv = e[k];
        int32_t rv = (k + 1 < en) ? e[k + 1] : e[k];
        int32_t base = (lv + rv) >> 1;
        out[2 * k + 1] = odd[k] + (base + m.predict(lv, rv));
        out[2 * k] = e[k];
    }
    if (en > on) out[2 * on] = e[on];
}

} // namespace prism::codec
