package glyphforge.codegen

import glyphforge.cli.VERSION
import glyphforge.core.Font
import glyphforge.core.Raster

/**
 * The glyph-to-code exporters: deterministic generators that turn a [Font]
 * into embeddable source in four flavors. The Kotlin, Java, and C outputs are
 * self-contained (no imports beyond the standard library) so retro projects
 * can drop them in; the test suite re-parses the emitted arrays and verifies
 * they rebuild the original pixels.
 */
enum class ExportFormat(val display: String, val extension: String) {
    KOTLIN("kotlin", "kt"),
    JAVA("java", "java"),
    C("c", "h"),
    TEXT("text", "txt");

    companion object {
        fun parse(s: String): ExportFormat = when (s.lowercase()) {
            "kotlin", "kt" -> KOTLIN
            "java" -> JAVA
            "c", "h", "c-header", "cheader" -> C
            "text", "txt" -> TEXT
            else -> throw IllegalArgumentException("unknown export format '$s' (use kotlin, java, c, or text)")
        }
    }
}

object Exporter {

    /** Rows as a list of byte values (or wider when the grid needs it). */
    private fun rowValues(g: glyphforge.core.Glyph): List<Int> {
        val v = g.width <= 8
        return (0 until g.height).map { y -> if (v) g.rowBits(y) and 0xFF else g.rowBits(y) }
    }

    private fun hexLit(value: Int, digits: Int): String =
        "0x" + value.toString(16).uppercase().padStart(digits, '0')

    private fun hexDigits(width: Int): Int = (width + 3) / 4

    /** Kotlin char literal, escaped for source. */
    fun ktChar(c: Char): String = when (c) {
        '\'' -> "'\\''"
        '\\' -> "'\\\\'"
        '\t' -> "'\\t'"
        else -> "'$c'"
    }

    /** Java char literal, escaped for source. */
    fun javaChar(c: Char): String = ktChar(c)

    /** C char literal for ASCII, else a hex code point integer. */
    fun cChar(c: Char): String {
        return if (c.code in 0x20..0x7E) {
            when (c) {
                '\'' -> "'\\''"
                '\\' -> "'\\\\'"
                else -> "'$c'"
            }
        } else {
            "0x${c.code.toString(16).uppercase().padStart(4, '0')}"
        }
    }

    fun export(font: Font, format: ExportFormat, rle: Boolean, packageName: String? = null): String = when (format) {
        ExportFormat.KOTLIN -> if (rle) kotlinRle(font, packageName) else kotlin(font, packageName)
        ExportFormat.JAVA -> java(font, packageName)
        ExportFormat.C -> if (rle) cRle(font) else c(font)
        ExportFormat.TEXT -> text(font)
    }

    private fun header(font: Font, extra: String = ""): String {
        val sb = StringBuilder()
        sb.append("// Generated by Glyphforge $VERSION. Do not edit.\n")
        sb.append("// Font: ${font.name}, ${font.cellWidth}x${font.cellHeight}, baseline ${font.baseline}, ")
        sb.append("default advance ${font.defaultAdvance}, ${font.glyphCount()} glyphs.")
        if (extra.isNotEmpty()) sb.append("\n// $extra")
        sb.append('\n')
        return sb.toString()
    }

    private fun safeClassName(name: String): String {
        val s = name.map { if (it.isLetterOrDigit() || it == '_') it else '_' }.joinToString("")
        val trimmed = s.trim('_')
        return if (trimmed.isEmpty()) "Font" else if (trimmed[0].isDigit()) "_$trimmed" else trimmed
    }

    // ------------------------------------------------------------------ Kotlin

    fun kotlin(font: Font, packageName: String? = null): String {
        val cls = safeClassName(font.name)
        val sb = StringBuilder()
        sb.append(header(font))
        if (!packageName.isNullOrBlank()) sb.append("\npackage $packageName\n")
        sb.append("""

/**
 * $cls - a ${font.cellWidth}x${font.cellHeight} pixel font exported from Glyphforge.
 * Rows are bit-packed: row y holds the pixels of row y, bit x = column x (LSB first).
 * Glyphs and their advances live in parallel arrays indexed by CODEPOINTS.
 */
object $cls {
    const val NAME: String = "${escaped(font.name)}"
    const val CELL_WIDTH: Int = ${font.cellWidth}
    const val CELL_HEIGHT: Int = ${font.cellHeight}
    const val BASELINE: Int = ${font.baseline}
    const val DEFAULT_ADVANCE: Int = ${font.defaultAdvance}

    /** Every character this font defines, sorted by code point. */
    val CODEPOINTS: CharArray = charArrayOf(${font.chars().joinToString(", ") { ktChar(it) }})

    /** Row bitmaps, parallel to CODEPOINTS. */
    val ROWS: Array<IntArray> = arrayOf(
""".trimStart('\n'))
        for (c in font.chars()) {
            sb.append("        intArrayOf(")
            sb.append((0 until font.cellHeight).joinToString(", ") { y ->
                hexLit(font.glyph(c)!!.rowBits(y), hexDigits(font.cellWidth))
            })
            sb.append("),\n")
        }
        sb.append("    )\n\n")
        sb.append("    /** Advance widths, parallel to CODEPOINTS. */\n")
        sb.append("    val ADVANCE: IntArray = intArrayOf(${font.chars().joinToString(", ") { font.advance(it).toString() }})\n")
        sb.append("""

    fun index(c: Char): Int {
        for (i in CODEPOINTS.indices) if (CODEPOINTS[i] == c) return i
        return -1
    }

    /** Row bitmaps for [c], or a blank grid when the font does not define it. */
    fun rows(c: Char): IntArray = index(c).let { if (it < 0) IntArray(CELL_HEIGHT) else ROWS[it] }

    /** Advance width for [c], defaulting to DEFAULT_ADVANCE. */
    fun advance(c: Char): Int = index(c).let { if (it < 0) DEFAULT_ADVANCE else ADVANCE[it] }

    fun pixel(c: Char, x: Int, y: Int): Boolean {
        if (x !in 0 until CELL_WIDTH || y !in 0 until CELL_HEIGHT) return false
        return (rows(c)[y] ushr x) and 1 == 1
    }

    /** Renders one glyph as [on]/[off] art. */
    fun render(c: Char, on: Char = '#', off: Char = ' '): List<String> {
        val r = rows(c)
        return (0 until CELL_HEIGHT).map { y ->
            (0 until CELL_WIDTH).joinToString("") { x -> if ((r[y] ushr x) and 1 == 1) on.toString() else off.toString() }
        }
    }

    /** Renders a string, honoring per-glyph advance widths. */
    fun renderText(text: String, on: Char = '#', off: Char = ' '): List<String> {
        val out = mutableListOf<String>()
        for (line in text.split('\n')) {
            val width = line.sumOf { advance(it) }
            for (y in 0 until CELL_HEIGHT) {
                val row = StringBuilder(width)
                for (c in line) {
                    val r = rows(c)
                    for (x in 0 until advance(c)) {
                        row.append(if ((r[y] ushr x) and 1 == 1) on else off)
                    }
                }
                out.add(row.toString())
            }
        }
        return out
    }
}
""".trimStart('\n'))
        return sb.toString()
    }

    fun kotlinRle(font: Font, packageName: String? = null): String {
        val cls = safeClassName(font.name) + "Rle"
        val sb = StringBuilder()
        sb.append(header(font, "RLE-packed streams"))
        if (!packageName.isNullOrBlank()) sb.append("\npackage $packageName\n")
        sb.append("""

/**
 * $cls - ${font.cellWidth}x${font.cellHeight} pixel font, compact RLE form.
 * Each stream is byte 0 = grid width, byte 1 = grid height, then per row y:
 * one byte run count, then (start, length) byte pairs of set pixels.
 */
object $cls {
    const val CELL_WIDTH: Int = ${font.cellWidth}
    const val CELL_HEIGHT: Int = ${font.cellHeight}
    const val DEFAULT_ADVANCE: Int = ${font.defaultAdvance}

    val CODEPOINTS: CharArray = charArrayOf(${font.chars().joinToString(", ") { ktChar(it) }})
    val ADVANCE: IntArray = intArrayOf(${font.chars().joinToString(", ") { font.advance(it).toString() }})

    /** Compact run-length streams, parallel to CODEPOINTS. */
    val STREAMS: Array<ByteArray> = arrayOf(
""".trimStart('\n'))
        for (c in font.chars()) {
            val bytes = Raster.packRle(font.glyph(c)!!)
            sb.append("        byteArrayOf(")
            sb.append(bytes.joinToString(", ") { (it.toInt() and 0xFF).toString() })
            sb.append("),\n")
        }
        sb.append("    )\n\n")
        sb.append("""

    fun index(c: Char): Int {
        for (i in CODEPOINTS.indices) if (CODEPOINTS[i] == c) return i
        return -1
    }

    fun advance(c: Char): Int = index(c).let { if (it < 0) DEFAULT_ADVANCE else ADVANCE[it] }

    /** Decodes and tests one pixel from a glyph's RLE stream. */
    fun pixel(c: Char, x: Int, y: Int): Boolean {
        val i = index(c)
        if (i < 0 || x !in 0 until CELL_WIDTH || y !in 0 until CELL_HEIGHT) return false
        val s = STREAMS[i]
        var k = 2
        for (row in 0 until CELL_HEIGHT) {
            if (k >= s.size) return false
            val n = s[k++].toInt() and 0xFF
            for (run in 0 until n) {
                if (k + 1 >= s.size) return false
                val start = s[k++].toInt() and 0xFF
                val len = s[k++].toInt() and 0xFF
                if (row == y && x >= start && x < start + len) return true
            }
        }
        return false
    }

    /** Number of bytes in a glyph's stream; smaller is more compact. */
    fun streamBytes(c: Char): Int = index(c).let { if (it < 0) 0 else STREAMS[it].size }
}
""".trimStart('\n'))
        return sb.toString()
    }

    // ------------------------------------------------------------------ Java

    fun java(font: Font, packageName: String? = null): String {
        val cls = safeClassName(font.name)
        val sb = StringBuilder()
        sb.append("// Generated by Glyphforge $VERSION. Do not edit.\n")
        sb.append("// Font: ${font.name}, ${font.cellWidth}x${font.cellHeight}, baseline ${font.baseline}, ")
        sb.append("default advance ${font.defaultAdvance}, ${font.glyphCount()} glyphs.\n")
        if (!packageName.isNullOrBlank()) sb.append("\npackage $packageName;\n")
        val rowType = if (font.cellWidth <= 8) "byte" else if (font.cellWidth <= 16) "short" else "int"
        sb.append("""

/**
 * $cls - a ${font.cellWidth}x${font.cellHeight} pixel font exported from Glyphforge.
 * Rows are bit-packed: row y holds the pixels of row y, bit x = column x (LSB first).
 * Glyphs and their advances live in parallel arrays indexed by CODEPOINTS.
 */
public final class $cls {
    private $cls() {}

    public static final String NAME = "${escaped(font.name)}";
    public static final int CELL_WIDTH = ${font.cellWidth};
    public static final int CELL_HEIGHT = ${font.cellHeight};
    public static final int BASELINE = ${font.baseline};
    public static final int DEFAULT_ADVANCE = ${font.defaultAdvance};

    /** Every character this font defines, sorted by code point. */
    public static final char[] CODEPOINTS = { ${font.chars().joinToString(", ") { javaChar(it) }} };

    /** Row bitmaps, parallel to CODEPOINTS. */
    public static final $rowType[][] ROWS = {
""".trimStart('\n'))
        for (c in font.chars()) {
            sb.append("        { ")
            sb.append((0 until font.cellHeight).joinToString(", ") { y ->
                hexLit(font.glyph(c)!!.rowBits(y), hexDigits(font.cellWidth))
            })
            sb.append(" },\n")
        }
        sb.append("    };\n\n")
        sb.append("    /** Advance widths, parallel to CODEPOINTS. */\n")
        sb.append("    public static final int[] ADVANCE = { ${font.chars().joinToString(", ") { font.advance(it).toString() }} };\n")
        sb.append("""

    public static int index(char c) {
        for (int i = 0; i < CODEPOINTS.length; i++) if (CODEPOINTS[i] == c) return i;
        return -1;
    }

    /** Row bitmaps for c, or a blank grid when the font does not define it. */
    public static $rowType[] rows(char c) {
        int i = index(c);
        return i < 0 ? new $rowType[CELL_HEIGHT] : ROWS[i];
    }

    /** Advance width for c, defaulting to DEFAULT_ADVANCE. */
    public static int advance(char c) {
        int i = index(c);
        return i < 0 ? DEFAULT_ADVANCE : ADVANCE[i];
    }

    public static boolean pixel(char c, int x, int y) {
        if (x < 0 || x >= CELL_WIDTH || y < 0 || y >= CELL_HEIGHT) return false;
        int r = rows(c)[y];
        return ((r >> x) & 1) == 1;
    }

    /** Renders one glyph into a String grid (on/off art). */
    public static String[] render(char c, char on, char off) {
        $rowType[] r = rows(c);
        String[] out = new String[CELL_HEIGHT];
        for (int y = 0; y < CELL_HEIGHT; y++) {
            StringBuilder sb = new StringBuilder();
            for (int x = 0; x < CELL_WIDTH; x++) {
                sb.append(((r[y] >> x) & 1) == 1 ? on : off);
            }
            out[y] = sb.toString();
        }
        return out;
    }
}
""".trimStart('\n'))
        return sb.toString()
    }

    // ------------------------------------------------------------------ C

    fun c(font: Font): String {
        val prefix = cPrefix(font.name)
        val up = prefix.uppercase()
        val rowType = if (font.cellWidth <= 8) "uint8_t" else if (font.cellWidth <= 16) "uint16_t" else "uint32_t"
        val sb = StringBuilder()
        sb.append("/* Generated by Glyphforge $VERSION. Do not edit. */\n")
        sb.append("/* Font: ${font.name}, ${font.cellWidth}x${font.cellHeight}, baseline ${font.baseline}, default advance ${font.defaultAdvance}, ${font.glyphCount()} glyphs. */\n")
        sb.append("#ifndef ${up}_FONT_H\n#define ${up}_FONT_H\n\n#include <stdint.h>\n\n")
        sb.append("#define ${up}_CELL_WIDTH  ${font.cellWidth}\n")
        sb.append("#define ${up}_CELL_HEIGHT ${font.cellHeight}\n")
        sb.append("#define ${up}_BASELINE    ${font.baseline}\n")
        sb.append("#define ${up}_DEFAULT_ADVANCE ${font.defaultAdvance}\n")
        sb.append("#define ${up}_GLYPH_COUNT ${font.glyphCount()}\n\n")
        for (c in font.chars()) {
            sb.append("static const $rowType ${prefix}_${cGlyphId(c)}[${font.cellHeight}] = { ")
            sb.append((0 until font.cellHeight).joinToString(", ") { y ->
                hexLit(font.glyph(c)!!.rowBits(y), hexDigits(font.cellWidth))
            })
            sb.append(" };\n")
        }
        sb.append("\nstruct ${prefix}_glyph {\n    int codepoint;\n    uint8_t advance;\n    const $rowType *rows;\n};\n\n")
        sb.append("static const struct ${prefix}_glyph ${prefix}_glyphs[${up}_GLYPH_COUNT] = {\n")
        for (c in font.chars()) {
            sb.append("    { ${cChar(c)}, ${font.advance(c)}, ${prefix}_${cGlyphId(c)} },\n")
        }
        sb.append("};\n\n")
        sb.append("static int ${prefix}_index(int c) {\n")
        sb.append("    for (int i = 0; i < ${up}_GLYPH_COUNT; i++) {\n")
        sb.append("        if (${prefix}_glyphs[i].codepoint == c) return i;\n")
        sb.append("    }\n    return -1;\n}\n\n")
        sb.append("static uint8_t ${prefix}_pixel(int c, int x, int y) {\n")
        sb.append("    if (x < 0 || x >= ${up}_CELL_WIDTH || y < 0 || y >= ${up}_CELL_HEIGHT) return 0;\n")
        sb.append("    int i = ${prefix}_index(c);\n")
        sb.append("    if (i < 0) return 0;\n")
        sb.append("    return (${prefix}_glyphs[i].rows[y] >> x) & 1u;\n}\n\n")
        sb.append("/* Fills out[0..(H*(W+1))-1] with the glyph rendered as on/off art (newline-separated rows). */\n")
        sb.append("static void ${prefix}_render(int c, char on, char off, char *out) {\n")
        sb.append("    int i = ${prefix}_index(c);\n")
        sb.append("    for (int y = 0; y < ${up}_CELL_HEIGHT; y++) {\n")
        sb.append("        for (int x = 0; x < ${up}_CELL_WIDTH; x++) {\n")
        sb.append("            out[y * (${up}_CELL_WIDTH + 1) + x] = (i >= 0 && (${prefix}_glyphs[i].rows[y] >> x) & 1u) ? on : off;\n")
        sb.append("        }\n")
        sb.append("        out[y * (${up}_CELL_WIDTH + 1) + ${up}_CELL_WIDTH] = '\\n';\n")
        sb.append("    }\n}\n\n")
        sb.append("#endif /* ${up}_FONT_H */\n")
        return sb.toString()
    }

    fun cRle(font: Font): String {
        val prefix = cPrefix(font.name)
        val up = prefix.uppercase()
        val sb = StringBuilder()
        sb.append("/* Generated by Glyphforge $VERSION. Do not edit. (compact RLE form) */\n")
        sb.append("/* Font: ${font.name}, ${font.cellWidth}x${font.cellHeight}, baseline ${font.baseline}, default advance ${font.defaultAdvance}, ${font.glyphCount()} glyphs. */\n")
        sb.append("#ifndef ${up}_RLE_H\n#define ${up}_RLE_H\n\n#include <stdint.h>\n\n")
        sb.append("#define ${up}_CELL_WIDTH  ${font.cellWidth}\n")
        sb.append("#define ${up}_CELL_HEIGHT ${font.cellHeight}\n")
        sb.append("#define ${up}_DEFAULT_ADVANCE ${font.defaultAdvance}\n")
        sb.append("#define ${up}_GLYPH_COUNT ${font.glyphCount()}\n\n")
        sb.append("/* Per-glyph packed streams: byte 0 = width, byte 1 = height, then per row:\n   run count byte, then (start, length) byte pairs. */\n")
        sb.append("static const uint8_t ${prefix}_streams[${up}_GLYPH_COUNT][] = {\n")
        for (c in font.chars()) {
            val bytes = Raster.packRle(font.glyph(c)!!)
            sb.append("    { ")
            sb.append(bytes.joinToString(", ") { (it.toInt() and 0xFF).toString() })
            sb.append(" },\n")
        }
        sb.append("};\n\n")
        sb.append("static const int ${prefix}_codepoints[${up}_GLYPH_COUNT] = {\n    ")
        sb.append(font.chars().joinToString(", ") { "${it.code}" })
        sb.append("\n};\n\n")
        sb.append("static const uint8_t ${prefix}_advance[${up}_GLYPH_COUNT] = {\n    ")
        sb.append(font.chars().joinToString(", ") { font.advance(it).toString() })
        sb.append("\n};\n\n")
        sb.append("static int ${prefix}_index(int c) {\n")
        sb.append("    for (int i = 0; i < ${up}_GLYPH_COUNT; i++) {\n")
        sb.append("        if (${prefix}_codepoints[i] == c) return i;\n")
        sb.append("    }\n    return -1;\n}\n\n")
        sb.append("static int ${prefix}_advance_for(int c) {\n")
        sb.append("    int i = ${prefix}_index(c);\n")
        sb.append("    return i < 0 ? ${up}_DEFAULT_ADVANCE : ${prefix}_advance[i];\n}\n\n")
        sb.append("static uint8_t ${prefix}_pixel(int c, int x, int y) {\n")
        sb.append("    int i = ${prefix}_index(c);\n")
        sb.append("    if (i < 0 || x < 0 || x >= ${up}_CELL_WIDTH || y < 0 || y >= ${up}_CELL_HEIGHT) return 0;\n")
        sb.append("    const uint8_t *s = ${prefix}_streams[i];\n")
        sb.append("    size_t k = 2;\n")
        sb.append("    for (int row = 0; row < ${up}_CELL_HEIGHT; row++) {\n")
        sb.append("        uint8_t n = s[k++];\n")
        sb.append("        for (uint8_t run = 0; run < n; run++) {\n")
        sb.append("            uint8_t start = s[k++], len = s[k++];\n")
        sb.append("            if (row == y && x >= start && x < start + len) return 1;\n")
        sb.append("        }\n")
        sb.append("    }\n    return 0;\n}\n\n")
        sb.append("#endif /* ${up}_RLE_H */\n")
        return sb.toString()
    }

    // ------------------------------------------------------------------ Text

    fun text(font: Font): String {
        val sb = StringBuilder()
        sb.append("${font.name} - ${font.cellWidth}x${font.cellHeight} pixel font, baseline ${font.baseline}, default advance ${font.defaultAdvance}, ${font.glyphCount()} glyphs\n")
        sb.append("Legend: # = pixel on, . = pixel off. Each glyph block is followed by its row hex and advance.\n\n")
        for (c in font.chars()) {
            val g = font.glyph(c)!!
            val label = if (c.isISOControl()) "U+${c.code.toString(16).uppercase().padStart(4, '0')}" else "'$c'"
            sb.append("$label U+${c.code.toString(16).uppercase().padStart(4, '0')} advance ${font.advance(c)}\n")
            for (line in Raster.toArt(g, '#', '.')) sb.append(line).append('\n')
            sb.append("rows ").append(Raster.rowHex(g).joinToString(" ")).append('\n')
            sb.append('\n')
        }
        return sb.toString()
    }

    // ------------------------------------------------------------------ helpers

    private fun cPrefix(name: String): String {
        val s = name.map { if (it.isLetterOrDigit() || it == '_') it else '_' }.joinToString("").trim('_')
        val base = if (s.isEmpty()) "glyphforge" else s.lowercase()
        return if (base[0].isDigit()) "f$base" else base
    }

    private fun cGlyphId(c: Char): String = when {
        c in 'a'..'z' || c in 'A'..'Z' || c in '0'..'9' -> c.toString()
        c == ' ' -> "space"
        else -> "u${c.code.toString(16)}"
    }

    private fun escaped(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"")
}