package glyphforge.codegen

import glyphforge.cli.VERSION
import glyphforge.core.Font

/**
 * The HTML specimen generator: turns a [Font] into a single, self-contained,
 * zero-dependency HTML page that acts as the browser frontend for the headless
 * engine. The page embeds the font's glyph bitmaps, advances, and kern pairs
 * as JavaScript data and renders any text live in ASCII or solid-block art
 * (kerning-aware, at any scale), plus a gallery of every glyph. A font
 * designer can open the page directly from disk or serve it anywhere.
 *
 * The output is deterministic: identical fonts produce identical pages, which
 * keeps the page diffable and testable.
 */
object Specimen {

    /** Builds the specimen page for [font]. [title] overrides the page title. */
    fun generate(font: Font, title: String? = null): String {
        val t = escapeHtml(title ?: "${font.name} - Glyphforge specimen")
        val data = buildData(font)
        return header(t, font, escapeHtml(font.name)) + data + script + footer()
    }

    private fun header(title: String, font: Font, name: String): String = """
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<style>
  :root { --bg:#101418; --fg:#d7e3e8; --muted:#7a8a92; --accent:#3ddc84; --on:#3ddc84; --off:#22303a; --card:#171d23; --border:#26323c; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--fg); font: 15px/1.5 ui-monospace, Menlo, Consolas, monospace; }
  header { padding: 28px 40px 12px; }
  h1 { margin:0; font-size: 26px; letter-spacing: .5px; }
  h1 .glyphforge { color: var(--accent); }
  .meta { color: var(--muted); margin: 6px 0 0; }
  main { padding: 0 40px 48px; }
  .controls { display:flex; flex-wrap:wrap; gap:16px; align-items:center; padding:16px 18px; background:var(--card); border:1px solid var(--border); border-radius:8px; margin:18px 0; }
  .controls label { color: var(--muted); display:flex; flex-direction:column; gap:6px; font-size:12px; }
  .controls input[type=text] { font: 15px/1.4 ui-monospace, monospace; padding:8px 10px; width: 46ch; background:var(--bg); color:var(--fg); border:1px solid var(--border); border-radius:6px; }
  .controls select, .controls input[type=number] { font: 14px ui-monospace, monospace; padding:7px 8px; background:var(--bg); color:var(--fg); border:1px solid var(--border); border-radius:6px; }
  .preview { display:flex; flex-direction:column; gap:10px; }
  .preview .ascii-out { margin:0; padding:18px; background:var(--card); border:1px solid var(--border); border-radius:8px; line-height:1.15; }
  .block-grid { display:grid; padding:18px; background:var(--card); border:1px solid var(--border); border-radius:8px; width:max-content; }
  .px { display:inline-block; }
  .px.on { background:var(--on); }
  .px.off { background:var(--off); }
  .ascii .px.on { background:none; }
  h2 { margin: 36px 0 10px; font-size: 17px; }
  .gallery { display:grid; grid-template-columns: repeat(auto-fill, minmax(90px, 1fr)); gap:10px; }
  .glyph-card { background:var(--card); border:1px solid var(--border); border-radius:8px; padding:12px; text-align:center; }
  .glyph-card .label { color: var(--muted); font-size: 11px; margin-bottom: 8px; }
  .glyph-card .sample { font-size: 22px; color: var(--fg); }
  .glyph-card .grid { display:grid; margin: 8px auto 0; width:max-content; }
  .glyph-card .cell { width:6px; height:6px; }
  .glyph-card .cell.on { background:var(--on); }
  .glyph-card .cell.off { background:var(--off); }
  .kerns { color: var(--muted); font-size: 12px; margin-top: 6px; }
  footer { padding: 10px 40px 30px; color: var(--muted); font-size: 12px; }
</style>
</head>
<body>
<header>
  <h1><span class="glyphforge">Glyphforge</span> specimen</h1>
  <p class="meta">$name - ${font.cellWidth}x${font.cellHeight} pixel font, baseline ${font.baseline}, default advance ${font.defaultAdvance}, ${font.glyphCount()} glyphs, ${font.kernCount()} kern pairs. Generated by Glyphforge $VERSION.</p>
</header>
<main>
  <section class="controls">
    <label>Text
      <input type="text" id="text" value="AVATAR To the rescue!" autocomplete="off">
    </label>
    <label>Mode
      <select id="mode">
        <option value="blocks" selected>blocks</option>
        <option value="ascii">ascii</option>
      </select>
    </label>
    <label>Scale
      <input type="number" id="scale" value="4" min="1" max="16" step="1">
    </label>
  </section>
  <section id="preview" class="preview"></section>
  <h2>Glyph gallery</h2>
  <section id="gallery" class="gallery"></section>
</main>
<footer>Generated by Glyphforge $VERSION. Kerning is applied live; the preview honors each glyph's advance width.</footer>
""".trimIndent() + "\n"

    /** The font data as a JavaScript object literal (one line per glyph). */
    private fun buildData(font: Font): String {
        val sb = StringBuilder()
        sb.append("<script>\n")
        sb.append("// Font data embedded by Glyphforge $VERSION. Do not edit.\n")
        sb.append("const FONT = {\n")
        sb.append("  name: '").append(escapeJs(font.name)).append("',\n")
        sb.append("  cellWidth: ").append(font.cellWidth).append(",\n")
        sb.append("  cellHeight: ").append(font.cellHeight).append(",\n")
        sb.append("  baseline: ").append(font.baseline).append(",\n")
        sb.append("  defaultAdvance: ").append(font.defaultAdvance).append(",\n")
        sb.append("  glyphs: [\n")
        for (c in font.chars()) {
            val g = font.glyph(c)!!
            sb.append("    { c: ").append(c.code)
                .append(", a: ").append(font.advance(c))
                .append(", r: [")
            for (y in 0 until g.height) {
                if (y > 0) sb.append(',')
                sb.append("0x").append(g.rowBits(y).toString(16).uppercase().padStart((font.cellWidth + 3) / 4, '0'))
            }
            sb.append("] },\n")
        }
        sb.append("  ],\n")
        sb.append("  kerns: [\n")
        for ((a, b, amount) in font.kernPairs()) {
            sb.append("    [ ").append(a.code).append(", ").append(b.code).append(", ").append(amount).append(" ],\n")
        }
        sb.append("  ]\n")
        sb.append("};\n")
        return sb.toString()
    }

    /** The (static) renderer and painter; string concatenation, no template literals. */
    private val script = """
function rowsOf(c) {
  for (var i = 0; i < FONT.glyphs.length; i++) if (FONT.glyphs[i].c === c) return FONT.glyphs[i].r;
  var blank = [];
  for (var y = 0; y < FONT.cellHeight; y++) blank.push(0);
  return blank;
}
function advanceOf(c) {
  for (var i = 0; i < FONT.glyphs.length; i++) if (FONT.glyphs[i].c === c) return FONT.glyphs[i].a;
  return FONT.defaultAdvance;
}
function kernOf(a, b) {
  for (var i = 0; i < FONT.kerns.length; i++) if (FONT.kerns[i][0] === a && FONT.kerns[i][1] === b) return FONT.kerns[i][2];
  return 0;
}
function lineCells(line) {
  var offsets = [];
  var col = 0;
  for (var i = 0; i < line.length; i++) {
    offsets.push(col);
    col += advanceOf(line.charCodeAt(i));
    if (i + 1 < line.length) col += kernOf(line.charCodeAt(i), line.charCodeAt(i + 1));
  }
  var width = line.length === 0 ? 0 : Math.max(1, col);
  var cells = [];
  for (var cx = 0; cx < width; cx++) {
    cells.push([]);
    for (var y = 0; y < FONT.cellHeight; y++) cells[cx].push(false);
  }
  for (var i = 0; i < line.length; i++) {
    var c = line.charCodeAt(i);
    var r = rowsOf(c);
    var a = advanceOf(c);
    for (var x = 0; x < a; x++) {
      var cx = offsets[i] + x;
      if (cx < 0 || cx >= width) continue;
      for (var y = 0; y < FONT.cellHeight; y++) cells[cx][y] = ((r[y] >> x) & 1) === 1;
    }
  }
  return { width: width, cells: cells };
}
function paintBlocks(cells, scale) {
  var grid = document.createElement('div');
  grid.className = 'block-grid';
  grid.style.gridTemplateColumns = 'repeat(' + cells.width + ', ' + scale + 'px)';
  for (var y = 0; y < FONT.cellHeight; y++) {
    for (var cx = 0; cx < cells.width; cx++) {
      var d = document.createElement('div');
      d.className = cells.cells[cx][y] ? 'px on' : 'px off';
      d.style.width = scale + 'px';
      d.style.height = scale + 'px';
      grid.appendChild(d);
    }
  }
  return grid;
}
function paintAscii(cells, scale) {
  var pre = document.createElement('pre');
  pre.className = 'ascii-out';
  pre.style.fontSize = scale + 'px';
  var lines = [];
  for (var y = 0; y < FONT.cellHeight; y++) {
    var s = '';
    for (var cx = 0; cx < cells.width; cx++) s += cells.cells[cx][y] ? '#' : '.';
    lines.push(s);
  }
  pre.textContent = lines.join('\n');
  return pre;
}
function preview() {
  var text = document.getElementById('text').value;
  var mode = document.getElementById('mode').value;
  var scale = parseInt(document.getElementById('scale').value, 10) || 1;
  var host = document.getElementById('preview');
  host.textContent = '';
  for (var i = 0; i < text.split('\n').length; i++) {
    var cells = lineCells(text.split('\n')[i]);
    var node = mode === 'ascii' ? paintAscii(cells, Math.max(scale, 8)) : paintBlocks(cells, scale);
    host.appendChild(node);
  }
}
function glyphGrid(glyph, cell) {
  var grid = document.createElement('div');
  grid.className = 'grid';
  grid.style.gridTemplateColumns = 'repeat(' + FONT.cellWidth + ', ' + cell + 'px)';
  for (var y = 0; y < FONT.cellHeight; y++) {
    for (var x = 0; x < FONT.cellWidth; x++) {
      var d = document.createElement('div');
      d.className = 'cell ' + (((glyph.r[y] >> x) & 1) === 1 ? 'on' : 'off');
      d.style.width = cell + 'px';
      d.style.height = cell + 'px';
      grid.appendChild(d);
    }
  }
  return grid;
}
function gallery() {
  var host = document.getElementById('gallery');
  for (var i = 0; i < FONT.glyphs.length; i++) {
    var g = FONT.glyphs[i];
    var card = document.createElement('div');
    card.className = 'glyph-card';
    var label = document.createElement('div');
    label.className = 'label';
    label.textContent = 'U+' + g.c.toString(16).toUpperCase().padStart(4, '0') + ' adv ' + g.a;
    var sample = document.createElement('div');
    sample.className = 'sample';
    sample.textContent = String.fromCharCode(g.c);
    card.appendChild(label);
    card.appendChild(sample);
    card.appendChild(glyphGrid(g, 6));
    host.appendChild(card);
  }
}
document.getElementById('text').addEventListener('input', preview);
document.getElementById('mode').addEventListener('change', preview);
document.getElementById('scale').addEventListener('input', preview);
preview();
gallery();
</script>
""".trimIndent()

    private fun footer(): String = "\n</body>\n</html>\n"

    private fun escapeHtml(s: String): String =
        s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")

    private fun escapeJs(s: String): String = s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
}