#pragma once
#include "prism/codec/wavelet.h"
#include <vector>
#include <cstdint>

namespace prism::codec {

// Learned wavelet-domain coefficient predictor (Route 4 / X6a, "beyond-predictive"
// paradigm, lever L1).
//
// Instead of coding a coefficient c, the residual path codes r = c - c_hat where
// c_hat is a regression over a CAUSAL window of already-reconstructed
// coefficients (same-subband 3x3 causal neighbourhood + parent + same-level
// sibling orientations). Because c_hat depends only on information that is
// available at decode time (strictly earlier in coding-major order), the round
// trip stays byte-exact and NO predictor state is transmitted: the weights are
// baked constants (invariant I29). This removes magnitude bits outright - the
// proven mechanism of L3C / Ballé hyperprior codecs (and the structural gap the
// X2 entropy diagnostic located: the bitplane coder is entropy-near-optimal, so
// the remaining bits live in the SOURCE entropy of the coefficient field).
//
// Reference: Mentzer et al., "Learning Convolutional Networks for Content-Weighted
// Image Compression", CVPR 2018 (scale-recursive learned pyramid, ~2.8-3.0 bpp
// lossless Kodak). Our predictor is a baked linear model per subband orientation
// (LL, HL, LH, HH), trained offline by ridge regression on real Kodak coefficients
// and shipped as constants in predictor_data.inc.

// One training / evaluation sample for the coefficient predictor.
struct PredictSample {
    int32_t target = 0;                 // true coefficient c
    // Features (8): [0]=median(left,up,upleft)  (JPEG-LS-style edge predictor, the
    // dominant nonlinear term), [1]=left, [2]=up, [3]=upleft, [4]=upright,
    // [5]=parent, [6]=sib1, [7]=sib2. The median is a strong nonlinear edge
    // predictor that collapses large residual magnitudes on edges (the
    // coefficients that set the bitplane max), which is what lets the residual
    // path actually shrink source entropy.
    int32_t feat[8] = {0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t orient = 0;                 // Subband::Orient 0..3 (selects the per-class model)
};

// Baked predictor weights: one linear model per orientation.
//   c_hat = bias[o] + sum_{k=0..7} w[o][k] * feat[k]
// An untrained (all-zero) model predicts c_hat = 0, so the residual path is
// byte-identical to the non-residual path and every test round-trips safely.
struct PredictWeights {
    float bias[4] = {0, 0, 0, 0};
    float w[4][8] = {{0, 0, 0, 0, 0, 0, 0, 0}};
};

struct CoefficientPredictor {
    // Build per-plane topology from a subband layout (orient/level/w/h in
    // forward() order). `order` is coding-major (LL first, then HL,LH,HH per
    // level coarse-to-fine); `parent[si]` / `sib1[si]` / `sib2[si]` are the
    // subband indices used by the causal window (or -1 when unavailable).
    static void build_topology(const std::vector<Subband>& subs,
                               std::vector<int>& order,
                               std::vector<int>& parent,
                               std::vector<int>& sib1,
                               std::vector<int>& sib2);

    // Predict c_hat (integer, rounded) for coefficient (x,y) in subband `si`.
    // `recon` holds reconstructed coefficients per subband in the SAME layout as
    // `subs`; only coefficients strictly earlier in coding order are read, so the
    // value is identical at encode (where recon == true c) and decode (where recon
    // is already reconstructed).
    int32_t predict(const std::vector<std::vector<int32_t>>& recon,
                    const std::vector<Subband>& subs,
                    const std::vector<int>& parent,
                    const std::vector<int>& sib1,
                    const std::vector<int>& sib2,
                    int si, int x, int y) const;

    // Offline sample collection (coding-major order), for training. Uses the
    // TRUE coefficient of each neighbour (recon == original subbands), mirroring
    // predict()'s causal window exactly so the trained model is symmetric.
    static void collect_samples(const std::vector<Subband>& subs,
                                std::vector<PredictSample>& out);

    // Read the baked weights (generated by `prism train-predictor`).
    const PredictWeights& weights() const { return weights_; }

private:
    PredictWeights weights_;
};

} // namespace prism::codec
