#pragma once
#include "prism/codec/wavelet.h"
#include <vector>
#include <cstdint>

namespace prism::codec {

// Learned wavelet-domain coefficient predictor (Route 4 / X6, "beyond-predictive"
// paradigm, levers L1/L2).
//
// Instead of coding a coefficient c, the residual path codes r = c - c_hat where
// c_hat is a regression over a CAUSAL window of already-reconstructed
// coefficients (same-subband 3x3 causal neighbourhood + parent + same-level
// sibling orientations). Because c_hat depends only on information that is
// available at decode time (strictly earlier in coding-major order), the round
// trip stays byte-exact and NO predictor state is transmitted: the weights are
// baked constants (invariant I29). This removes magnitude bits outright - the
// proven mechanism of L3C / Ballé hyperprior codecs (and the structural gap the
// X2 entropy diagnostic located: the bitplane coder is entropy-near-optimal, so
// the remaining bits live in the SOURCE entropy of the coefficient field).
//
// X6a used a per-orientation LINEAR model (8 features) and reached ~72% variance
// explained; the residual path then HURT because a 72%-explained predictor leaves
// too many formerly-exact-zero coefficients as nonzero residuals (each pays a
// significance + sign bit the original source got for free). X6b replaces the
// linear model with a small per-orientation MLP over a RICHER 16-feature window
// and trains it to minimise the residual's L1 norm (a tight proxy for the
// Laplacian-optimal bitplane codelength), lifting variance explained past the
// ~85% threshold at which the residual entropy finally beats the source entropy.

// Number of predictor input features (X6b, enriched window).
constexpr int PRED_NF = 16;
// Hidden-layer width of the per-orientation predictor MLP.
constexpr int PRED_NH = 32;

// One training / evaluation sample for the coefficient predictor.
struct PredictSample {
    int32_t target = 0;                       // true coefficient c
    float feat[PRED_NF] = {0.0f};             // normalised window features
    uint8_t orient = 0;                       // Subband::Orient 0..3 (selects the per-class model)
};

// Baked predictor MLP weights: one small network per orientation (LL, HL, LH, HH).
//   h[j] = relu( b1[o][j] + sum_i w1[o][j][i] * feat[i] )
//   c_hat = b2[o] + sum_j w2[o][j] * h[j]
// An untrained (all-zero) model predicts c_hat = 0, so the residual path is
// byte-identical to the non-residual path and every test round-trips safely.
struct PredMLP {
    float w1[4][PRED_NH][PRED_NF] = {{0.0f}};
    float b1[4][PRED_NH] = {0.0f};
    float w2[4][PRED_NH] = {0.0f};
    float b2[4] = {0.0f};
};

struct CoefficientPredictor {
    // Build per-plane topology from a subband layout (orient/level/w/h in
    // forward() order). `order` is coding-major (LL first, then HL,LH,HH per
    // level coarse-to-fine); `parent[si]` / `sib1[si]` / `sib2[si]` are the
    // subband indices used by the causal window (or -1 when unavailable).
    static void build_topology(const std::vector<Subband>& subs,
                               std::vector<int>& order,
                               std::vector<int>& parent,
                               std::vector<int>& sib1,
                               std::vector<int>& sib2);

    // Predict c_hat (integer, rounded) for coefficient (x,y) in subband `si`.
    // `recon` holds reconstructed coefficients per subband in the SAME layout as
    // `subs`; only coefficients strictly earlier in coding order are read, so the
    // value is identical at encode (where recon == true c) and decode (where recon
    // is already reconstructed).
    int32_t predict(const std::vector<std::vector<int32_t>>& recon,
                    const std::vector<Subband>& subs,
                    const std::vector<int>& parent,
                    const std::vector<int>& sib1,
                    const std::vector<int>& sib2,
                    int si, int x, int y) const;

    // Offline sample collection (coding-major order), for training. Uses the
    // TRUE coefficient of each neighbour (recon == original subbands), mirroring
    // predict()'s causal window exactly so the trained model is symmetric.
    static void collect_samples(const std::vector<Subband>& subs,
                                std::vector<PredictSample>& out);

    // Default-construct with the shipped baked weights (generated by
    // `prism train-predictor`); construct from an explicit set to evaluate a
    // freshly solved model (e.g. the training diagnostic in the CLI).
    CoefficientPredictor();
    explicit CoefficientPredictor(const PredMLP& w) : mlp_(w) {}

    // Read the active weights.
    const PredMLP& weights() const { return mlp_; }

private:
    PredMLP mlp_;
};

} // namespace prism::codec
