// Route 6C (issue #130, lever C): per-fine-context-cluster transmitted P(0)
// histograms via a fixed, baked property tree.
//
// R6-B blended a model COARSER than the cold-starting EMA (12 subband classes),
// so blending could only hurt (it landed +6% worse than the pure-EMA floor).
// R6-C instead transmits ONE P(0) value per FINE-CONTEXT CLUSTER: a bounded
// partition of the adaptive model's context space produced by a FIXED, baked
// decision tree. The cluster id is a pure function of the learned feature vector
// `LCFeat`, so it is computed identically at encode and decode time and costs
// ZERO transmitted bytes; only the K per-leaf P(0)*M values (the `r6c_p0`
// vector) are sent (invariant I29 preserved).
//
// R6-C0 (the first cut, now abandoned) used a fixed coarse quantization that
// DROPPED `nmag`/`ownmag`/`ppos`, coarsening the fine context and merging
// clusters whose true P(0) differ - exactly R6-B's failure class. R6-C1 (this
// build) keeps every dimension that is SYMMETRIC in the R6-C residual walk as a
// live split axis, so the transmitted backbone groups fine contexts by
// p0-homogeneity and no longer repeats R6-C0's loss.
//
// The tree does NOT split on `lc_mag`/`lc_sig`: in the R6-C residual frame those
// are always zero (no luma cross-component reference is threaded through the
// residual coder), so splitting on them would be degenerate. This is a
// deliberate, correct choice, not a regression. `pmag` IS available (it is the
// parent subband's already-coded magnitude, threaded identically at encode and
// decode) and is a live split axis.
//
// See `route6c_tree.inc` (generated by `prism train-r6c`) for the baked node
// array and the `r6c_leaf` lookup. `r6c_K()` == R6C_K (pinned 1024).
#pragma once
#include "prism/codec/learned_ctx.h"
#include <cstdint>

namespace prism::codec {

// Number of transmitted clusters (baked tree leaves). R6C_K = 1024 (pinned).
uint32_t r6c_K();

// Cluster (leaf) id in [0, r6c_K()) for a learned feature vector. FIXED function
// of `f`, identical at encode/decode, so it is never transmitted.
uint32_t r6c_leaf(const LCFeat& f);

// Blend weight W between the transmitted per-cluster static P(0) backbone and
// the learned adaptive model (EMA + MLP). 0 = pure learned, 1 = pure
// transmitted. Default 0.6 (frozen by addendum-27); overridable at runtime via
// `prism wavelet-r6c --w W` / `bench-r6c --w W` without rebuild.
float r6c_w();
void set_r6c_w(float v);

} // namespace prism::codec

// Baked tree data (generated by `prism train-r6c`; committed for reproducibility).
#include "prism/codec/route6c_tree.inc"
