#pragma once
#include "prism/types.h"
#include <cstdint>
#include <vector>

namespace prism::codec {

constexpr int R10_H = 16; // Route 10 hidden units (mirrors Route10MLP::H for the .inc)

// Route 10 learned nonlinear MLP predict step (issue #130).
//
// Replaces the linear Le Gall 5/3 *predict* `odd - (lv + rv) >> 1` with
//   odd - ((lv + rv) >> 1 + mlp(lv, rv))
// where mlp is a tiny 2->16->1 ReLU integer MLP that consumes the RAW neighbour
// values lv, rv (a continuous, full-neighbour function class a piecewise LUT
// cannot express). The *update* step stays linear Le Gall, so the lift remains
// EXACTLY reversible (invariant I26): decode adds the identical integer mlp.
//
// Weights are int16 fixed-point: every linear product is scaled by Q = 1024 and
// combined via an arithmetic right shift (= floor division by Q), matching the
// numpy integer-sim in prism/scripts/train_route10.py bit-for-bit in the domain.
struct Route10MLP {
    static constexpr int H = 16;
    static constexpr int Q = 1024; // 2 ** 10
    const int16_t (*W1)[2] = nullptr;
    const int16_t* b1 = nullptr;
    const int16_t* W2 = nullptr;
    int16_t b2 = 0;

    // Integer MLP prediction of the Le Gall base correction.
    int32_t predict(int32_t lv, int32_t rv) const;
};

// Baked weights (generated by prism/scripts/train_route10.py ->
// prism/src/codec/route10_mlp_data.inc, included by route10_mlp.cpp).
Route10MLP baked_route10_mlp();

// Forward / inverse 1D lifting steps using the learned MLP predict.
void forward_learned_mlp(const std::vector<int32_t>& even, const std::vector<int32_t>& odd,
                         std::vector<int32_t>& out_even, std::vector<int32_t>& out_odd);
void inverse_learned_mlp(const std::vector<int32_t>& even, const std::vector<int32_t>& odd,
                         std::vector<int32_t>& out);

} // namespace prism::codec
