/* Generated by Glyphforge 1.0.0. Do not edit. */
/* Font: Pico3x5, 3x5, baseline 4, default advance 3, 38 glyphs. */
#ifndef PICO3X5_FONT_H
#define PICO3X5_FONT_H

#include <stdint.h>

#define PICO3X5_CELL_WIDTH  3
#define PICO3X5_CELL_HEIGHT 5
#define PICO3X5_BASELINE    4
#define PICO3X5_DEFAULT_ADVANCE 3
#define PICO3X5_GLYPH_COUNT 38

static const uint8_t pico3x5_space[5] = { 0x0, 0x0, 0x0, 0x0, 0x0 };
static const uint8_t pico3x5_u2e[5] = { 0x0, 0x0, 0x0, 0x0, 0x2 };
static const uint8_t pico3x5_0[5] = { 0x2, 0x5, 0x5, 0x5, 0x2 };
static const uint8_t pico3x5_1[5] = { 0x2, 0x3, 0x2, 0x2, 0x2 };
static const uint8_t pico3x5_2[5] = { 0x3, 0x4, 0x2, 0x1, 0x3 };
static const uint8_t pico3x5_3[5] = { 0x3, 0x4, 0x2, 0x4, 0x3 };
static const uint8_t pico3x5_4[5] = { 0x5, 0x5, 0x7, 0x4, 0x4 };
static const uint8_t pico3x5_5[5] = { 0x7, 0x1, 0x3, 0x4, 0x3 };
static const uint8_t pico3x5_6[5] = { 0x2, 0x1, 0x3, 0x5, 0x2 };
static const uint8_t pico3x5_7[5] = { 0x7, 0x4, 0x2, 0x2, 0x2 };
static const uint8_t pico3x5_8[5] = { 0x2, 0x5, 0x2, 0x5, 0x2 };
static const uint8_t pico3x5_9[5] = { 0x2, 0x5, 0x6, 0x4, 0x2 };
static const uint8_t pico3x5_A[5] = { 0x2, 0x5, 0x7, 0x5, 0x5 };
static const uint8_t pico3x5_B[5] = { 0x3, 0x5, 0x3, 0x5, 0x3 };
static const uint8_t pico3x5_C[5] = { 0x2, 0x5, 0x1, 0x5, 0x2 };
static const uint8_t pico3x5_D[5] = { 0x3, 0x5, 0x5, 0x5, 0x3 };
static const uint8_t pico3x5_E[5] = { 0x7, 0x1, 0x3, 0x1, 0x7 };
static const uint8_t pico3x5_F[5] = { 0x7, 0x1, 0x3, 0x1, 0x1 };
static const uint8_t pico3x5_G[5] = { 0x2, 0x5, 0x1, 0x5, 0x6 };
static const uint8_t pico3x5_H[5] = { 0x5, 0x5, 0x7, 0x5, 0x5 };
static const uint8_t pico3x5_I[5] = { 0x7, 0x2, 0x2, 0x2, 0x7 };
static const uint8_t pico3x5_J[5] = { 0x4, 0x4, 0x4, 0x5, 0x2 };
static const uint8_t pico3x5_K[5] = { 0x5, 0x5, 0x3, 0x5, 0x5 };
static const uint8_t pico3x5_L[5] = { 0x1, 0x1, 0x1, 0x1, 0x7 };
static const uint8_t pico3x5_M[5] = { 0x5, 0x7, 0x5, 0x5, 0x5 };
static const uint8_t pico3x5_N[5] = { 0x7, 0x5, 0x5, 0x5, 0x5 };
static const uint8_t pico3x5_O[5] = { 0x2, 0x5, 0x5, 0x5, 0x2 };
static const uint8_t pico3x5_P[5] = { 0x3, 0x5, 0x3, 0x1, 0x1 };
static const uint8_t pico3x5_Q[5] = { 0x2, 0x5, 0x5, 0x2, 0x4 };
static const uint8_t pico3x5_R[5] = { 0x3, 0x5, 0x3, 0x5, 0x5 };
static const uint8_t pico3x5_S[5] = { 0x6, 0x1, 0x2, 0x4, 0x3 };
static const uint8_t pico3x5_T[5] = { 0x7, 0x2, 0x2, 0x2, 0x2 };
static const uint8_t pico3x5_U[5] = { 0x5, 0x5, 0x5, 0x5, 0x2 };
static const uint8_t pico3x5_V[5] = { 0x5, 0x5, 0x5, 0x2, 0x2 };
static const uint8_t pico3x5_W[5] = { 0x5, 0x5, 0x7, 0x5, 0x5 };
static const uint8_t pico3x5_X[5] = { 0x5, 0x5, 0x2, 0x5, 0x5 };
static const uint8_t pico3x5_Y[5] = { 0x5, 0x5, 0x2, 0x2, 0x2 };
static const uint8_t pico3x5_Z[5] = { 0x7, 0x4, 0x2, 0x1, 0x7 };

struct pico3x5_glyph {
    int codepoint;
    uint8_t advance;
    const uint8_t *rows;
};

static const struct pico3x5_glyph pico3x5_glyphs[PICO3X5_GLYPH_COUNT] = {
    { ' ', 3, pico3x5_space },
    { '.', 2, pico3x5_u2e },
    { '0', 3, pico3x5_0 },
    { '1', 3, pico3x5_1 },
    { '2', 3, pico3x5_2 },
    { '3', 3, pico3x5_3 },
    { '4', 3, pico3x5_4 },
    { '5', 3, pico3x5_5 },
    { '6', 3, pico3x5_6 },
    { '7', 3, pico3x5_7 },
    { '8', 3, pico3x5_8 },
    { '9', 3, pico3x5_9 },
    { 'A', 3, pico3x5_A },
    { 'B', 3, pico3x5_B },
    { 'C', 3, pico3x5_C },
    { 'D', 3, pico3x5_D },
    { 'E', 3, pico3x5_E },
    { 'F', 3, pico3x5_F },
    { 'G', 3, pico3x5_G },
    { 'H', 3, pico3x5_H },
    { 'I', 3, pico3x5_I },
    { 'J', 3, pico3x5_J },
    { 'K', 3, pico3x5_K },
    { 'L', 3, pico3x5_L },
    { 'M', 3, pico3x5_M },
    { 'N', 3, pico3x5_N },
    { 'O', 3, pico3x5_O },
    { 'P', 3, pico3x5_P },
    { 'Q', 3, pico3x5_Q },
    { 'R', 3, pico3x5_R },
    { 'S', 3, pico3x5_S },
    { 'T', 3, pico3x5_T },
    { 'U', 3, pico3x5_U },
    { 'V', 3, pico3x5_V },
    { 'W', 3, pico3x5_W },
    { 'X', 3, pico3x5_X },
    { 'Y', 3, pico3x5_Y },
    { 'Z', 3, pico3x5_Z },
};

/* Kerning pairs (left, right) -> advance adjustment; empty when the font has none. */
#define PICO3X5_KERN_COUNT 5
static const int pico3x5_kern_left[PICO3X5_KERN_COUNT > 0 ? PICO3X5_KERN_COUNT : 1] = { 'A', 'A', 'A', 'L', 'V' };
static const int pico3x5_kern_right[PICO3X5_KERN_COUNT > 0 ? PICO3X5_KERN_COUNT : 1] = { 'T', 'V', 'W', 'T', 'A' };
static const int8_t pico3x5_kern_amount[PICO3X5_KERN_COUNT > 0 ? PICO3X5_KERN_COUNT : 1] = { -1, -1, -1, -1, -1 };

static int pico3x5_kern(int a, int b) {
    for (int i = 0; i < PICO3X5_KERN_COUNT; i++) {
        if (pico3x5_kern_left[i] == a && pico3x5_kern_right[i] == b) return pico3x5_kern_amount[i];
    }
    return 0;
}

static int pico3x5_index(int c) {
    for (int i = 0; i < PICO3X5_GLYPH_COUNT; i++) {
        if (pico3x5_glyphs[i].codepoint == c) return i;
    }
    return -1;
}

static uint8_t pico3x5_pixel(int c, int x, int y) {
    if (x < 0 || x >= PICO3X5_CELL_WIDTH || y < 0 || y >= PICO3X5_CELL_HEIGHT) return 0;
    int i = pico3x5_index(c);
    if (i < 0) return 0;
    return (pico3x5_glyphs[i].rows[y] >> x) & 1u;
}

/* Fills out[0..(H*(W+1))-1] with the glyph rendered as on/off art (newline-separated rows). */
static void pico3x5_render(int c, char on, char off, char *out) {
    int i = pico3x5_index(c);
    for (int y = 0; y < PICO3X5_CELL_HEIGHT; y++) {
        for (int x = 0; x < PICO3X5_CELL_WIDTH; x++) {
            out[y * (PICO3X5_CELL_WIDTH + 1) + x] = (i >= 0 && (pico3x5_glyphs[i].rows[y] >> x) & 1u) ? on : off;
        }
        out[y * (PICO3X5_CELL_WIDTH + 1) + PICO3X5_CELL_WIDTH] = '\n';
    }
}

#endif /* PICO3X5_FONT_H */
