// Package perapp implements Linux per-app Tor routing via torsocks.
//
// Binding choice (research spec): torsocks by default (fail-closed, correct
// DNS, minimal config). Targets that would silently bypass the LD_PRELOAD
// shim - static binaries, non-ELF files, setuid/setgid - are refused with a
// clear error redirecting to transparent mode (M3), never executed
// torified-in-name-only.
package perapp

import (
	"debug/elf"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// TorsocksConf is the minimal fail-closed torsocks profile.
func TorsocksConf(torAddr string, torPort int) string {
	return fmt.Sprintf(`# Generated by torshim. Do not edit.
TorAddress %s
TorPort %d
OnionAddrRange 127.42.42.0/24
IsolatePID 1
AllowInbound 0
AllowOutboundLocalhost 0
`, torAddr, torPort)
}

// WriteConf writes a torsocks config file with restrictive permissions.
func WriteConf(path, torAddr string, torPort int) error {
	return os.WriteFile(path, []byte(TorsocksConf(torAddr, torPort)), 0o600)
}

// libCandidates are searched in order for libtorsocks.so.
var libCandidates = []string{
	"/usr/lib/x86_64-linux-gnu/torsocks/libtorsocks.so",
	"/usr/lib/aarch64-linux-gnu/torsocks/libtorsocks.so",
	"/usr/lib/torsocks/libtorsocks.so",
	"/usr/local/lib/torsocks/libtorsocks.so",
	"/usr/lib64/torsocks/libtorsocks.so",
}

// FindLib locates libtorsocks.so. TORSOCKS_LIB overrides the search.
// An error means torsocks is not installed: fail closed, do not exec.
func FindLib() (string, error) {
	if override := os.Getenv("TORSOCKS_LIB"); override != "" {
		if fi, err := os.Stat(override); err == nil && !fi.IsDir() {
			return override, nil
		}
		return "", fmt.Errorf("perapp: TORSOCKS_LIB=%q not usable", override)
	}
	for _, p := range libCandidates {
		if fi, err := os.Stat(p); err == nil && !fi.IsDir() {
			return p, nil
		}
	}
	if out, err := exec.LookPath("torsocks"); err == nil {
		// The torsocks wrapper exists; its library lives beside it.
		// Probe ldconfig output as a last resort.
		if lib, lerr := ldconfigProbe(); lerr == nil {
			return lib, nil
		}
		_ = out
	}
	return "", fmt.Errorf("perapp: libtorsocks.so not found (install package \"torsocks\"); refusing to run without the shim")
}

func ldconfigProbe() (string, error) {
	out, err := exec.Command("ldconfig", "-p").Output()
	if err != nil {
		return "", err
	}
	for _, ln := range strings.Split(string(out), "\n") {
		ln = strings.TrimSpace(ln)
		if strings.HasPrefix(ln, "libtorsocks.so") {
			fields := strings.Fields(ln)
			last := fields[len(fields)-1]
			if fi, err := os.Stat(last); err == nil && !fi.IsDir() {
				return last, nil
			}
		}
	}
	return "", fmt.Errorf("perapp: libtorsocks.so absent from ldconfig")
}

// Classification describes whether the LD_PRELOAD shim can cover a target.
type Classification int

const (
	// ShimOK means a dynamically linked ELF (or a script whose interpreter
	// is resolved through the normal loader path).
	ShimOK Classification = iota
	// ShimBypass means the shim would be silently ignored: static binaries
	// (Go static, Rust musl, raw syscalls), non-ELF executables, or
	// setuid/setgid files (the loader ignores LD_PRELOAD for them).
	ShimBypass
)

// ClassifyTarget inspects path and reports whether torsocks can cover it.
// Scripts (#!) resolve to their interpreter, which is checked recursively
// with a small depth cap. Anything unrecognized fails closed (ShimBypass).
func ClassifyTarget(path string) (Classification, string, error) {
	resolved := path
	for depth := 0; depth < 4; depth++ {
		f, err := os.Open(resolved)
		if err != nil {
			return ShimBypass, "", fmt.Errorf("perapp: open %s: %w", resolved, err)
		}
		head := make([]byte, 4)
		n, _ := f.Read(head)
		f.Close()
		if n < 4 {
			return ShimBypass, "unreadable executable header", nil
		}
		if head[0] == '#' && head[1] == '!' {
			interp, err := scriptInterpreter(resolved)
			if err != nil {
				return ShimBypass, "", err
			}
			if !filepath.IsAbs(interp) {
				interp, err = exec.LookPath(interp)
				if err != nil {
					return ShimBypass, fmt.Sprintf("script interpreter %q not on PATH", interp), nil
				}
			}
			resolved = interp
			continue
		}
		if head[0] != 0x7f || head[1] != 'E' || head[2] != 'L' || head[3] != 'F' {
			return ShimBypass, "non-ELF executable bypasses LD_PRELOAD silently", nil
		}
		fi, err := os.Stat(resolved)
		if err != nil {
			return ShimBypass, "", err
		}
		if fi.Mode()&(os.ModeSetuid|os.ModeSetgid) != 0 {
			return ShimBypass, "setuid/setgid binaries ignore LD_PRELOAD", nil
		}
		dyn, err := isDynamicELF(resolved)
		if err != nil {
			return ShimBypass, "", err
		}
		if !dyn {
			return ShimBypass, "statically linked binary bypasses LD_PRELOAD silently (use transparent mode or app-native socks5h)", nil
		}
		return ShimOK, "", nil
	}
	return ShimBypass, "interpreter chain too deep", nil
}

func scriptInterpreter(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	first, _, _ := strings.Cut(string(raw), "\n")
	first = strings.TrimPrefix(first, "#!")
	fields := strings.Fields(first)
	if len(fields) == 0 {
		return "", fmt.Errorf("perapp: empty shebang in %s", path)
	}
	if filepath.Base(fields[0]) == "env" && len(fields) > 1 {
		return fields[1], nil
	}
	return fields[0], nil
}

// isDynamicELF reports whether the ELF file has a PT_INTERP segment.
// Presence of an interpreter means the dynamic loader runs, which is what
// honors LD_PRELOAD. Static (and static-PIE) binaries have none.
func isDynamicELF(path string) (bool, error) {
	f, err := elf.Open(path)
	if err != nil {
		return false, fmt.Errorf("perapp: parse ELF %s: %w", path, err)
	}
	defer f.Close()
	for _, prog := range f.Progs {
		if prog.Type == elf.PT_INTERP {
			return true, nil
		}
	}
	return false, nil
}

// Env builds the torsocks environment for a child process.
func Env(base []string, libPath, confPath string) []string {
	env := make([]string, 0, len(base)+4)
	env = append(env, base...)
	env = append(env,
		"LD_PRELOAD="+libPath,
		"TORSOCKS_CONF_FILE="+confPath,
		"TORSOCKS_ISOLATE_PID=1",
	)
	return env
}

// RunResult carries the child exit code.
type RunResult struct {
	ExitCode int
}

// Run executes app argv under torsocks against the given SOCKS endpoint.
// It fails closed: missing shim, bypass-class targets, and readiness gaps
// are errors, never silent bypasses.
func Run(socksAddr string, argv []string, extraEnv []string, confDir string) (RunResult, error) {
	if len(argv) == 0 {
		return RunResult{}, fmt.Errorf("perapp: no application given")
	}
	bin := argv[0]
	if !strings.Contains(bin, string(os.PathSeparator)) {
		lp, err := exec.LookPath(bin)
		if err != nil {
			return RunResult{}, fmt.Errorf("perapp: %q not found on PATH: %w", bin, err)
		}
		bin = lp
	}
	class, reason, err := ClassifyTarget(bin)
	if err != nil {
		return RunResult{}, err
	}
	if class == ShimBypass {
		return RunResult{}, fmt.Errorf("perapp: refusing %s: %s", bin, reason)
	}
	lib, err := FindLib()
	if err != nil {
		return RunResult{}, err
	}
	host, port := splitAddr(socksAddr)
	confPath := filepath.Join(confDir, "torsocks.conf")
	if err := WriteConf(confPath, host, port); err != nil {
		return RunResult{}, fmt.Errorf("perapp: write torsocks conf: %w", err)
	}
	cmd := exec.Command(bin, argv[1:]...)
	cmd.Env = Env(os.Environ(), lib, confPath)
	for _, kv := range extraEnv {
		cmd.Env = append(cmd.Env, kv)
	}
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return RunResult{ExitCode: ee.ExitCode()}, nil
		}
		return RunResult{}, fmt.Errorf("perapp: exec %s: %w", bin, err)
	}
	return RunResult{ExitCode: 0}, nil
}

func splitAddr(addr string) (string, int) {
	host, portStr, err := splitHostPort(addr)
	if err != nil {
		return "127.0.0.1", 9050
	}
	var port int
	fmt.Sscanf(portStr, "%d", &port)
	if port <= 0 {
		port = 9050
	}
	if host == "" {
		host = "127.0.0.1"
	}
	return host, port
}

func splitHostPort(addr string) (string, string, error) {
	i := strings.LastIndex(addr, ":")
	if i < 0 {
		return "", "", fmt.Errorf("no port")
	}
	return addr[:i], addr[i+1:], nil
}
